'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { resolveColorValue, resolveDiagramStyleConfig, type PostextConfig, type Resource, type VDTDocument } from 'postext';
import { renderToEpub, type EpubCover, type EpubLayout, type EpubWarning } from 'postext-epub';
import { useBookPlan, useSandboxSelector, useSandboxStateGetter } from '../context/SandboxContext';
import { composeBookMemo } from '../book/compose';
import { layOutBookPrint } from '../book/printChain';
import type { Chapter } from '../book/types';
import { ensureConfigFontsLoaded, onCustomFontsChanged } from '../controls/fontLoader';
import { withHyphenationLocale } from '../controls/hyphenation';
import { ensureResourceImages } from '../controls/resourceImages';
import { renderCoverImage } from '../covers/useAutoCover';
import { bookCoverPicture, collectEpubFonts, epubResourceBytes, RENDERED_COVER_WIDTH, usableCover } from '../epub/inputs';
import { epubFileName, epubMetadataOf, type EpubBookIdentity } from '../epub/metadata';
import { downloadBytes } from '../storage/persistence';
import { useLayoutWorker } from '../worker/useLayoutWorker';
import { perfSpan } from '../perf/marks';
import { announce } from '../ui/announcer';
import { EpubPreview, type EpubGenerationProgress } from './EpubPreview';
import type { EpubReaderHandle, EpubReaderPosition } from './EpubReader';
import { EpubToolbar } from './EpubToolbar';
import { useFloatingToolbarShell } from './useFloatingToolbarShell';

/** A warning of the last generation: the writer's, or a family the
 *  Sandbox left out of the file. */
export type EpubNotice = EpubWarning | { kind: 'fontWithheld'; family: string };

const noticeKey = (n: EpubNotice): string =>
  n.kind === 'missingImage' ? `img:${n.fileId}`
    : n.kind === 'unsupported' ? `x:${n.detail}`
      : n.kind === 'missingFont' ? `font:${n.family}:${n.weight ?? ''}:${n.style ?? ''}`
        : `withheld:${n.family}`;

/** The generated file and what it was made from. */
interface Generated {
  bytes: Uint8Array;
  layout: EpubLayout;
  title: string;
}

/** The EPUB 3 tab: the whole book written as an EPUB in the browser, in the
 *  rendition picked in the tab bar (a fixed layout or a reflowable book),
 *  shown by a small reader that opens the generated file itself, and
 *  downloaded as it is. Like the PDF tab it lays the book out chapter by
 *  chapter and regenerates on request; a change of rendition regenerates
 *  at once. */
export function EpubViewport() {
  const chapters = useSandboxSelector((s) => s.chapters);
  const plan = useBookPlan();
  const config = useSandboxSelector((s) => s.config);
  const resources = useSandboxSelector((s) => s.resources);
  const storeReady = useSandboxSelector((s) => s.storeReady);
  const locale = useSandboxSelector((s) => s.locale);
  const layout = useSandboxSelector((s) => s.epubLayout);
  const labels = useSandboxSelector((s) => s.labels);
  const getState = useSandboxStateGetter();
  const layoutWorker = useLayoutWorker('pdf');

  const [generated, setGenerated] = useState<Generated | null>(null);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [progress, setProgress] = useState<EpubGenerationProgress | null>(null);
  const [dirty, setDirty] = useState(false);
  const [notices, setNotices] = useState<EpubNotice[]>([]);
  const [position, setPosition] = useState<EpubReaderPosition | null>(null);
  const [fontScale, setFontScale] = useState(1);
  const readerRef = useRef<EpubReaderHandle | null>(null);
  const abortRef = useRef<AbortController | null>(null);
  const hasAutoGeneratedRef = useRef(false);
  const failedRef = useRef(false);
  const renderedRef = useRef<{ chapters: readonly Chapter[]; config: PostextConfig; resources: Resource[] } | null>(null);

  const effectiveConfig = useMemo((): PostextConfig => withHyphenationLocale(config, locale), [config, locale]);

  // The end of a generation is said through the live region (WCAG 4.1.3).
  const wasGeneratingRef = useRef(false);
  useEffect(() => {
    if (generating) { wasGeneratingRef.current = true; return; }
    if (!wasGeneratingRef.current) return;
    wasGeneratingRef.current = false;
    if (error) announce(`${labels.epubError}: ${error}`);
    else if (generated) announce(labels.epubReady);
  }, [generating, error, generated, labels.epubError, labels.epubReady]);

  const regenerate = useCallback(async () => {
    abortRef.current?.abort();
    const controller = new AbortController();
    abortRef.current = controller;
    const { signal } = controller;
    const snapshot = { chapters, config: effectiveConfig, resources };
    const snapshotLayout = layout;
    setGenerating(true);
    setError(null);
    setProgress({ phase: 'layout', done: 0, total: plan.chapters.length });
    failedRef.current = false;
    const total = perfSpan('epub.total', { layout: snapshotLayout });
    const found: EpubNotice[] = [];
    const seen = new Set<string>();
    // A family left out is said once, not again for each face it lacks.
    const withheldFamilies = new Set<string>();
    const note = (n: EpubNotice) => {
      const key = noticeKey(n);
      if (seen.has(key) || (n.kind === 'missingFont' && withheldFamilies.has(n.family))) return;
      seen.add(key);
      found.push(n);
      console.warn('[EpubViewport]', n);
    };
    try {
      await ensureConfigFontsLoaded(snapshot.config);
      signal.throwIfAborted();
      // The whole book, always: an EPUB is the book, not a chapter.
      const docs: VDTDocument[] = await layOutBookPrint({
        plan,
        chapters: snapshot.chapters,
        resources: snapshot.resources,
        config: snapshot.config,
        build: layoutWorker.build,
        onChapter: (index, count) => setProgress({ phase: 'layout', done: index, total: count }),
      });
      signal.throwIfAborted();
      if (docs.length === 0) throw new Error('No chapters to write');

      setProgress({ phase: 'inputs', done: 0, total: 1 });
      const state = getState();
      const project = state.activeProjectId ? state.projects.find((p) => p.id === state.activeProjectId) : undefined;
      const preset = project ? undefined : state.presetSummaries.find((p) => p.id === state.activePresetId);
      const identity: EpubBookIdentity | null = project
        ? { kind: 'project', id: project.id, name: project.name }
        : preset
          ? { kind: 'preset', id: preset.id, locale: state.presetApplied?.locale ?? state.locale, name: preset.name }
          : null;
      const metadata = epubMetadataOf(composeBookMemo(snapshot.chapters).metadata, snapshot.config, identity, locale);
      const [{ fonts, withheld }, cover] = await Promise.all([
        collectEpubFonts(snapshot.config, docs),
        epubCoverOf(docs[0]!, snapshot, metadata.title, { projectThumbnail: project?.thumbnail, presetThumbnailUrl: preset?.thumbnailUrl }),
      ]);
      for (const family of withheld) {
        note({ kind: 'fontWithheld', family });
        withheldFamilies.add(family);
      }
      signal.throwIfAborted();

      const bytes = await renderToEpub(docs, {
        layout: snapshotLayout,
        metadata,
        fonts,
        resourceBytes: epubResourceBytes(),
        ...(cover ? { cover } : {}),
        onProgress: (p) => setProgress({ phase: p.phase, done: p.done, total: p.total }),
        onWarning: note,
        signal,
      });
      signal.throwIfAborted();
      total.end({ kb: Math.round(bytes.byteLength / 1024), chapters: docs.length });
      setGenerated({ bytes, layout: snapshotLayout, title: metadata.title });
      setNotices(found);
      renderedRef.current = snapshot;
      setDirty(false);
    } catch (err) {
      if (signal.aborted) return;
      total.end({ error: true });
      console.error('[EpubViewport] Generation error:', err);
      setError(err instanceof Error ? err.message : String(err));
      setGenerated(null);
      setNotices([]);
      failedRef.current = true;
    } finally {
      if (abortRef.current === controller) {
        abortRef.current = null;
        setGenerating(false);
        setProgress(null);
      }
    }
  }, [chapters, effectiveConfig, resources, layout, plan, layoutWorker, getState, locale]);

  // Leaving the tab stops a generation under way. A first generation
  // stopped that way is run again if the tab comes back (React's strict
  // mode mounts it twice).
  useEffect(() => () => {
    if (!abortRef.current) return;
    abortRef.current.abort();
    if (renderedRef.current === null) hasAutoGeneratedRef.current = false;
  }, []);

  // A change of rendition is a request for the other file: regenerate now,
  // the file on screen taken down first.
  const generatedLayoutRef = useRef(layout);
  useEffect(() => {
    if (!hasAutoGeneratedRef.current || generatedLayoutRef.current === layout) return;
    generatedLayoutRef.current = layout;
    setGenerated(null);
    setPosition(null);
    void regenerate();
  }, [layout, regenerate]);

  // Dirty = the book, the settings or the resources changed since the
  // last file was written.
  useEffect(() => {
    const rendered = renderedRef.current;
    if (!hasAutoGeneratedRef.current || !rendered) return;
    if (rendered.chapters !== chapters || rendered.config !== effectiveConfig || rendered.resources !== resources) setDirty(true);
  }, [chapters, effectiveConfig, resources]);

  // Custom families landing after a generation (see the PDF tab).
  const regenerateRef = useRef(regenerate);
  regenerateRef.current = regenerate;
  useEffect(() => onCustomFontsChanged(() => {
    if (renderedRef.current !== null) setDirty(true);
    else if (failedRef.current) void regenerateRef.current();
  }), []);

  // The first file once the store has hydrated (resources come from
  // IndexedDB after mount).
  useEffect(() => {
    if (!storeReady || hasAutoGeneratedRef.current) return;
    hasAutoGeneratedRef.current = true;
    void regenerate();
  }, [storeReady, regenerate]);

  const handleDownload = useCallback(() => {
    if (!generated) return;
    downloadBytes(generated.bytes, epubFileName(generated.title), 'application/epub+zip');
  }, [generated]);

  const shell = useFloatingToolbarShell('epub', generating || dirty);
  const reflowable = generated?.layout === 'reflowable';

  return (
    <div className="relative h-full w-full" {...shell.containerProps}>
      <EpubPreview
        bytes={generated?.bytes ?? null}
        generating={generating}
        progress={progress}
        error={error}
        fontScale={fontScale}
        readerRef={readerRef}
        onPosition={setPosition}
      />
      <div {...shell.hoverStripProps} />
      <EpubToolbar
        generating={generating}
        dirty={dirty}
        pinned={shell.pinned}
        hidden={shell.hidden}
        fileSize={generated?.bytes.byteLength ?? null}
        reflowable={reflowable}
        position={generated ? position : null}
        fontScale={fontScale}
        notices={notices}
        onRegenerate={regenerate}
        onTogglePin={shell.togglePin}
        onDownload={handleDownload}
        onPrevious={() => readerRef.current?.previous()}
        onNext={() => readerRef.current?.next()}
        onGoToPosition={(n) => readerRef.current?.goToPosition(n)}
        onGoTo={(href) => readerRef.current?.goTo(href)}
        onFontScale={setFontScale}
        {...shell.toolbarHoverProps}
      />
    </div>
  );
}

/** The cover: the book's own picture when it is a bitmap large enough,
 *  else its first page painted at {@link RENDERED_COVER_WIDTH}. Either is a
 *  picture of the first page (the Sandbox's covers are captures of it), so
 *  the fixed layout keeps it as the cover image without a page of its own. */
async function epubCoverOf(
  first: VDTDocument,
  snapshot: { config: PostextConfig; resources: Resource[] },
  title: string,
  source: Parameters<typeof bookCoverPicture>[0],
): Promise<EpubCover | null> {
  const picture = await bookCoverPicture(source);
  const own = picture ? await usableCover(picture.bytes, picture.mime, title) : null;
  if (own) return { ...own, showsFirstPage: true };
  const page = first.pages[0];
  if (!page) return null;
  // The page's pictures as the canvas paints them.
  const ds = resolveDiagramStyleConfig(snapshot.config.diagramStyle);
  const ink = ds.singleInk ? resolveColorValue(ds.inkColor, snapshot.config.colorPalette, ds.inkColor).hex : null;
  await ensureResourceImages(snapshot.resources, ink).catch(() => false);
  if (typeof document !== 'undefined' && document.fonts) await document.fonts.ready;
  const image = await renderCoverImage(page, first, true, { width: RENDERED_COVER_WIDTH, trimmed: true });
  if (!image || image === 'missing') return null;
  return { bytes: new Uint8Array(image.bytes), mediaType: 'image/jpeg', alt: title, showsFirstPage: true };
}
