'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  resolveDebugConfig,
  resolvePdfGenerationConfig,
  type HyphenationLocale,
  type PostextConfig,
} from 'postext';
import { renderToPdf } from 'postext-pdf';
import { useSandboxSelector } from '../context/SandboxContext';
import { ensureConfigFontsLoaded } from '../controls/fontLoader';
import { useLayoutWorker } from '../worker/useLayoutWorker';
import { PdfPreview } from './PdfPreview';
import { PdfToolbar } from './PdfToolbar';
import { createPdfFontProvider } from './pdfFontProvider';
import { useFloatingToolbarShell } from './useFloatingToolbarShell';

const LOCALE_TO_HYPHENATION: Record<string, HyphenationLocale> = {
  en: 'en-us', es: 'es', fr: 'fr', de: 'de', it: 'it', pt: 'pt', ca: 'ca', nl: 'nl',
};

export function PdfViewport() {
  const markdown = useSandboxSelector((s) => s.markdown);
  const config = useSandboxSelector((s) => s.config);
  const locale = useSandboxSelector((s) => s.locale);
  const [bytesUrl, setBytesUrl] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  // Dirty = inputs changed since the last successful render. Canvas/HTML
  // auto-relayout, but the PDF viewer only regenerates on explicit request,
  // so the toolbar needs to announce that the preview is out of date.
  const [dirty, setDirty] = useState(false);
  const bytesRef = useRef<Uint8Array | null>(null);
  const providerRef = useRef(createPdfFontProvider());
  const currentUrlRef = useRef<string | null>(null);
  const hasAutoGeneratedRef = useRef(false);
  const renderedMarkdownRef = useRef<string | null>(null);
  const renderedConfigRef = useRef<PostextConfig | null>(null);
  const layoutWorker = useLayoutWorker();

  const effectiveConfig = useMemo((): PostextConfig => {
    if (config.bodyText?.hyphenation?.locale) return config;
    const hypLocale = LOCALE_TO_HYPHENATION[locale] ?? 'en-us';
    return {
      ...config,
      bodyText: {
        ...config.bodyText,
        hyphenation: {
          ...config.bodyText?.hyphenation,
          locale: hypLocale,
        },
      },
    };
  }, [config, locale]);

  const regenerate = useCallback(async () => {
    setGenerating(true);
    setError(null);
    const snapshotMarkdown = markdown;
    const snapshotConfig = effectiveConfig;
    try {
      await ensureConfigFontsLoaded(snapshotConfig);
      const doc = await layoutWorker.build({ markdown: snapshotMarkdown }, snapshotConfig);
      const debug = resolveDebugConfig(snapshotConfig.debug);
      const pdfGen = resolvePdfGenerationConfig(snapshotConfig.pdfGeneration);
      const bytes = await renderToPdf(doc, {
        fontProvider: providerRef.current,
        pageNegative: debug.pageNegative.enabled,
        outlines: pdfGen.outlines,
        colorSpace: pdfGen.forceColorSpace ? pdfGen.colorSpace : 'rgb',
      });
      bytesRef.current = bytes;
      const copy = bytes.slice();
      const blob = new Blob([copy.buffer], { type: 'application/pdf' });
      const url = URL.createObjectURL(blob);
      if (currentUrlRef.current) URL.revokeObjectURL(currentUrlRef.current);
      currentUrlRef.current = url;
      setBytesUrl(url);
      renderedMarkdownRef.current = snapshotMarkdown;
      renderedConfigRef.current = snapshotConfig;
      setDirty(false);
    } catch (err) {
      console.error('[PdfViewport] Render error:', err);
      setError(err instanceof Error ? err.message : String(err));
      bytesRef.current = null;
    } finally {
      setGenerating(false);
    }
  }, [markdown, effectiveConfig, layoutWorker]);

  // Dirty = current markdown/config differ from the snapshot of the last
  // successful render. Set whenever either drifts; cleared inside regenerate.
  useEffect(() => {
    if (!hasAutoGeneratedRef.current) return;
    if (renderedMarkdownRef.current === null) return;
    const changed =
      renderedMarkdownRef.current !== markdown ||
      renderedConfigRef.current !== effectiveConfig;
    if (changed) setDirty(true);
  }, [markdown, effectiveConfig]);

  // Auto-generate on first mount.
  useEffect(() => {
    if (hasAutoGeneratedRef.current) return;
    hasAutoGeneratedRef.current = true;
    void regenerate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    return () => {
      if (currentUrlRef.current) {
        URL.revokeObjectURL(currentUrlRef.current);
        currentUrlRef.current = null;
      }
    };
  }, []);

  const handleDownload = useCallback(() => {
    const bytes = bytesRef.current;
    if (!bytes) return;
    const copy = bytes.slice();
    const blob = new Blob([copy.buffer], { type: 'application/pdf' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    const title = markdown.match(/^#\s+(.+)$/m)?.[1]?.trim() ?? 'document';
    a.download = `${title.replace(/[^a-z0-9-_]+/gi, '-')}.pdf`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }, [markdown]);

  const handlePrint = useCallback(() => {
    if (!bytesUrl) return;
    const iframe = document.querySelector<HTMLIFrameElement>('iframe[data-postext-pdf="true"]');
    if (!iframe?.contentWindow) return;
    try {
      iframe.contentWindow.focus();
      iframe.contentWindow.print();
    } catch {
      window.open(bytesUrl, '_blank');
    }
  }, [bytesUrl]);

  // Dirty also forces visibility: the recalc button must be reachable the
  // moment something goes stale, otherwise the floating toolbar may be off
  // screen and the user can't act on the arrow cue.
  const shell = useFloatingToolbarShell('pdf', generating || dirty);

  return (
    <div className="relative h-full w-full" {...shell.containerProps}>
      <PdfPreview
        bytesUrl={bytesUrl}
        generating={generating}
        error={error}
      />
      <div {...shell.hoverStripProps} />
      <PdfToolbar
        onRegenerate={regenerate}
        onDownload={handleDownload}
        onPrint={handlePrint}
        onTogglePin={shell.togglePin}
        canDownload={!!bytesUrl && !generating}
        canPrint={!!bytesUrl && !generating}
        generating={generating}
        pinned={shell.pinned}
        hidden={shell.hidden}
        dirty={dirty}
        {...shell.toolbarHoverProps}
      />
    </div>
  );
}
