'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  buildDocument,
  createMeasurementCache,
  resolveDebugConfig,
  type HyphenationLocale,
  type PostextConfig,
} from 'postext';
import { renderToPdf } from 'postext-pdf';
import { useSandboxSelector } from '../context/SandboxContext';
import { ensureConfigFontsLoaded } from '../controls/fontLoader';
import { PdfPreview } from './PdfPreview';
import { PdfToolbar } from './PdfToolbar';
import { createPdfFontProvider } from './pdfFontProvider';

const LOCALE_TO_HYPHENATION: Record<string, HyphenationLocale> = {
  en: 'en-us', es: 'es', fr: 'fr', de: 'de', it: 'it', pt: 'pt', ca: 'ca', nl: 'nl',
};

export function PdfViewport() {
  const markdown = useSandboxSelector((s) => s.markdown);
  const config = useSandboxSelector((s) => s.config);
  const locale = useSandboxSelector((s) => s.locale);
  const [bytesUrl, setBytesUrl] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const bytesRef = useRef<Uint8Array | null>(null);
  const providerRef = useRef(createPdfFontProvider());
  const currentUrlRef = useRef<string | null>(null);
  const hasAutoGeneratedRef = useRef(false);

  const effectiveConfig = useMemo((): PostextConfig => {
    if (config.bodyText?.hyphenation?.locale) return config;
    const hypLocale = LOCALE_TO_HYPHENATION[locale] ?? 'en-us';
    return {
      ...config,
      bodyText: {
        ...config.bodyText,
        hyphenation: {
          ...config.bodyText?.hyphenation,
          locale: hypLocale,
        },
      },
    };
  }, [config, locale]);

  const regenerate = useCallback(async () => {
    setGenerating(true);
    setError(null);
    try {
      await ensureConfigFontsLoaded(effectiveConfig);
      const cache = createMeasurementCache();
      const doc = buildDocument({ markdown: markdown }, effectiveConfig, cache);
      const debug = resolveDebugConfig(effectiveConfig.debug);
      const bytes = await renderToPdf(doc, {
        fontProvider: providerRef.current,
        pageNegative: debug.pageNegative.enabled,
      });
      bytesRef.current = bytes;
      const copy = bytes.slice();
      const blob = new Blob([copy.buffer], { type: 'application/pdf' });
      const url = URL.createObjectURL(blob);
      if (currentUrlRef.current) URL.revokeObjectURL(currentUrlRef.current);
      currentUrlRef.current = url;
      setBytesUrl(url);
    } catch (err) {
      console.error('[PdfViewport] Render error:', err);
      setError(err instanceof Error ? err.message : String(err));
      bytesRef.current = null;
    } finally {
      setGenerating(false);
    }
  }, [markdown, effectiveConfig]);

  // Auto-generate on first mount.
  useEffect(() => {
    if (hasAutoGeneratedRef.current) return;
    hasAutoGeneratedRef.current = true;
    void regenerate();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    return () => {
      if (currentUrlRef.current) {
        URL.revokeObjectURL(currentUrlRef.current);
        currentUrlRef.current = null;
      }
    };
  }, []);

  const handleDownload = useCallback(() => {
    const bytes = bytesRef.current;
    if (!bytes) return;
    const copy = bytes.slice();
    const blob = new Blob([copy.buffer], { type: 'application/pdf' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    const title = markdown.match(/^#\s+(.+)$/m)?.[1]?.trim() ?? 'document';
    a.download = `${title.replace(/[^a-z0-9-_]+/gi, '-')}.pdf`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }, [markdown]);

  const handlePrint = useCallback(() => {
    if (!bytesUrl) return;
    const iframe = document.querySelector<HTMLIFrameElement>('iframe[data-postext-pdf="true"]');
    if (!iframe?.contentWindow) return;
    try {
      iframe.contentWindow.focus();
      iframe.contentWindow.print();
    } catch {
      window.open(bytesUrl, '_blank');
    }
  }, [bytesUrl]);

  return (
    <div className="relative h-full w-full">
      <PdfPreview
        bytesUrl={bytesUrl}
        generating={generating}
        error={error}
      />
      <PdfToolbar
        onRegenerate={regenerate}
        onDownload={handleDownload}
        onPrint={handlePrint}
        canDownload={!!bytesUrl && !generating}
        canPrint={!!bytesUrl && !generating}
        generating={generating}
      />
    </div>
  );
}
