'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  resolveDebugConfig,
  resolvePdfGenerationConfig,
  type HyphenationLocale,
  type PostextConfig,
  type Resource,
} from 'postext';
import { renderToPdf } from 'postext-pdf';
import { useSandboxLabels, useSandboxSelector, useLayoutSource, withLayoutOverride } from '../context/SandboxContext';
import type { ComposedBook } from '../book/types';
import { ensureConfigFontsLoaded, onCustomFontsChanged } from '../controls/fontLoader';
import { useLayoutWorker } from '../worker/useLayoutWorker';
import { buildPdfResourceBytes } from './pdfResourceBytes';
import { PdfPreview } from './PdfPreview';
import { PdfToolbar } from './PdfToolbar';
import { createPdfFontProvider } from './pdfFontProvider';
import { useFloatingToolbarShell } from './useFloatingToolbarShell';

const LOCALE_TO_HYPHENATION: Record<string, HyphenationLocale> = {
  en: 'en-us', es: 'es', fr: 'fr', de: 'de', it: 'it', pt: 'pt', ca: 'ca', nl: 'nl',
};

export function PdfViewport() {
  const { book, scope, configOverride } = useLayoutSource();
  const labels = useSandboxLabels();
  const config = useSandboxSelector((s) => s.config);
  const resources = useSandboxSelector((s) => s.resources);
  const storeReady = useSandboxSelector((s) => s.storeReady);
  const locale = useSandboxSelector((s) => s.locale);
  const [bytesUrl, setBytesUrl] = useState<string | null>(null);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  // Dirty = inputs changed since the last successful render. Canvas/HTML
  // auto-relayout, but the PDF viewer only regenerates on explicit request,
  // so the toolbar needs to announce that the preview is out of date.
  const [dirty, setDirty] = useState(false);
  const bytesRef = useRef<Uint8Array | null>(null);
  const providerRef = useRef(createPdfFontProvider());
  const currentUrlRef = useRef<string | null>(null);
  const hasAutoGeneratedRef = useRef(false);
  const renderedSourceRef = useRef<ComposedBook | null>(null);
  const renderedConfigRef = useRef<PostextConfig | null>(null);
  const renderedResourcesRef = useRef<Resource[] | null>(null);
  const layoutWorker = useLayoutWorker();

  const effectiveConfig = useMemo((): PostextConfig => {
    const base = withLayoutOverride(config, configOverride);
    if (base.bodyText?.hyphenation?.locale) return base;
    const hypLocale = LOCALE_TO_HYPHENATION[locale] ?? 'en-us';
    return {
      ...base,
      bodyText: {
        ...base.bodyText,
        hyphenation: {
          ...base.bodyText?.hyphenation,
          locale: hypLocale,
        },
      },
    };
  }, [config, configOverride, locale]);

  const regenerate = useCallback(async () => {
    setGenerating(true);
    setError(null);
    const snapshotSource = book;
    const snapshotConfig = effectiveConfig;
    const snapshotResources = resources;
    try {
      await ensureConfigFontsLoaded(snapshotConfig);
      const doc = await layoutWorker.build(
        { markdown: snapshotSource.markdown, metadata: snapshotSource.metadata, resources: snapshotResources },
        snapshotConfig,
      );
      const debug = resolveDebugConfig(snapshotConfig.debug);
      const pdfGen = resolvePdfGenerationConfig(snapshotConfig.pdfGeneration);
      const resourceBytes = await buildPdfResourceBytes(snapshotResources, snapshotConfig);
      const bytes = await renderToPdf(doc, {
        fontProvider: providerRef.current,
        pageNegative: debug.pageNegative.enabled,
        outlines: pdfGen.outlines,
        colorSpace: pdfGen.forceColorSpace ? pdfGen.colorSpace : 'rgb',
        resourceBytes: (fileId) => resourceBytes.get(fileId),
      });
      bytesRef.current = bytes;
      const copy = bytes.slice();
      const blob = new Blob([copy.buffer], { type: 'application/pdf' });
      const url = URL.createObjectURL(blob);
      if (currentUrlRef.current) URL.revokeObjectURL(currentUrlRef.current);
      currentUrlRef.current = url;
      setBytesUrl(url);
      renderedSourceRef.current = snapshotSource;
      renderedConfigRef.current = snapshotConfig;
      renderedResourcesRef.current = snapshotResources;
      setDirty(false);
    } catch (err) {
      console.error('[PdfViewport] Render error:', err);
      setError(err instanceof Error ? err.message : String(err));
      bytesRef.current = null;
    } finally {
      setGenerating(false);
    }
  }, [book, effectiveConfig, resources, layoutWorker]);

  // Dirty = current markdown/config/resources differ from the snapshot of the
  // last successful render. Set whenever any drifts; cleared inside regenerate.
  useEffect(() => {
    if (!hasAutoGeneratedRef.current) return;
    if (renderedSourceRef.current === null) return;
    const changed =
      renderedSourceRef.current !== book ||
      renderedConfigRef.current !== effectiveConfig ||
      renderedResourcesRef.current !== resources;
    if (changed) setDirty(true);
  }, [book, effectiveConfig, resources]);

  // A custom family whose definition lands after the last render (a preset
  // finishing its load, an upload from the Fonts panel) leaves the PDF
  // painted from stale bytes; flag it like any other input change.
  useEffect(() => {
    return onCustomFontsChanged(() => {
      if (renderedConfigRef.current !== null) setDirty(true);
    });
  }, []);

  // Auto-generate once the store has hydrated: resources arrive from
  // IndexedDB after mount, and a build before then renders every `:ref` as
  // an unresolved "?" — which this viewport would keep, since it only
  // regenerates on request.
  useEffect(() => {
    if (!storeReady || hasAutoGeneratedRef.current) return;
    hasAutoGeneratedRef.current = true;
    void regenerate();
  }, [storeReady, regenerate]);

  useEffect(() => {
    return () => {
      if (currentUrlRef.current) {
        URL.revokeObjectURL(currentUrlRef.current);
        currentUrlRef.current = null;
      }
    };
  }, []);

  const handleDownload = useCallback(() => {
    const bytes = bytesRef.current;
    if (!bytes) return;
    const copy = bytes.slice();
    const blob = new Blob([copy.buffer], { type: 'application/pdf' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    const metaTitle = typeof book.metadata.title === 'string' ? book.metadata.title : undefined;
    const title = metaTitle ?? book.markdown.match(/^#\s+(.+)$/m)?.[1]?.trim() ?? 'document';
    a.download = `${title.replace(/[^a-z0-9-_]+/gi, '-')}.pdf`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }, [book]);

  const handlePrint = useCallback(() => {
    if (!bytesUrl) return;
    const iframe = document.querySelector<HTMLIFrameElement>('iframe[data-postext-pdf="true"]');
    if (!iframe?.contentWindow) return;
    try {
      iframe.contentWindow.focus();
      iframe.contentWindow.print();
    } catch {
      window.open(bytesUrl, '_blank');
    }
  }, [bytesUrl]);

  // Dirty also forces visibility: the recalc button must be reachable the
  // moment something goes stale, otherwise the floating toolbar may be off
  // screen and the user can't act on the arrow cue.
  const shell = useFloatingToolbarShell('pdf', generating || dirty);

  return (
    <div className="relative h-full w-full" {...shell.containerProps}>
      <PdfPreview
        bytesUrl={bytesUrl}
        generating={generating}
        error={error}
      />
      {scope === 'chapter' && (
        <span
          className="pointer-events-none absolute top-3 left-3 z-10 rounded-full border px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide"
          style={{ borderColor: 'var(--gilt)', color: 'var(--gilt)', backgroundColor: 'var(--background)' }}
        >
          {labels.pdfChapterOnlyTag}
        </span>
      )}
      <div {...shell.hoverStripProps} />
      <PdfToolbar
        onRegenerate={regenerate}
        onDownload={handleDownload}
        onPrint={handlePrint}
        onTogglePin={shell.togglePin}
        canDownload={!!bytesUrl && !generating}
        canPrint={!!bytesUrl && !generating}
        generating={generating}
        pinned={shell.pinned}
        hidden={shell.hidden}
        dirty={dirty}
        {...shell.toolbarHoverProps}
      />
    </div>
  );
}
