import type { SandboxLabels } from './labels';

export const DEFAULT_LABELS: SandboxLabels = {
  configuration: 'Configuration',
  resources: 'Resources',
  markdownEditor: 'Markdown Editor',
  canvas: 'Canvas',
  html: 'HTML',
  pdf: 'PDF',
  comingSoon: 'Coming soon',
  resourcesComingSoonDescription: 'Resource management will be available in a future version.',
  pdfComingSoonDescription: 'PDF export will be available in a future version.',
  page: 'Page',
  pageBackgroundColor: 'Background Color',
  pageBackgroundColorTooltip: 'Background color of the page',
  pageSize: 'Page Size',
  pageSizeTooltip: 'Standard page format or custom dimensions',
  custom: 'Custom',
  width: 'Width',
  widthTooltip: 'Custom page width',
  height: 'Height',
  heightTooltip: 'Custom page height',
  marginTop: 'Top Margin',
  marginBottom: 'Bottom Margin',
  marginLeft: 'Left Margin',
  marginRight: 'Right Margin',
  marginsTooltip: 'Space between the page edge and the content area',
  dpi: 'DPI',
  dpiTooltip: 'Dots per inch — controls the resolution of the page',
  cutLines: 'Cut Lines',
  cutLinesTooltip: 'Show trim marks at the page corners for print cutting',
  cutLinesBleed: 'Bleed',
  cutLinesBleedTooltip: 'Extra area beyond the trim edge — backgrounds extend into this zone to prevent white edges after cutting',
  cutLinesMarkLength: 'Mark Length',
  cutLinesMarkLengthTooltip: 'Length of each crop mark line',
  cutLinesMarkOffset: 'Mark Offset',
  cutLinesMarkOffsetTooltip: 'Gap between the trim edge and the start of the crop mark',
  cutLinesMarkWidth: 'Mark Width',
  cutLinesMarkWidthTooltip: 'Stroke thickness of the crop mark lines',
  cutLinesColor: 'Mark Color',
  cutLinesColorTooltip: 'Color of the crop mark lines',
  baselineGrid: 'Baseline Grid',
  baselineGridTooltip: 'Show horizontal lines to align text baselines',
  baselineGridColor: 'Grid Color',
  baselineGridColorTooltip: 'Color of the baseline grid lines',
  baselineGridLineWidth: 'Line Width',
  baselineGridLineWidthTooltip: 'Thickness of the baseline grid lines',
  debug: 'Debug',
  debugCursorSync: 'Sync Cursor',
  debugCursorSyncTooltip: 'Show the editor cursor position live on the canvas preview',
  debugCursorSyncColor: 'Cursor Color',
  debugCursorSyncColorTooltip: 'Color of the cursor indicator drawn over the canvas',
  debugSelectionSync: 'Sync Selection',
  debugSelectionSyncTooltip: 'Highlight the editor text selection live on the canvas preview',
  debugSelectionSyncColor: 'Selection Color',
  debugSelectionSyncColorTooltip: 'Fill color of the selection highlight drawn over the canvas',
  debugLooseLines: 'Loose Lines',
  debugLooseLinesTooltip: 'Highlight justified lines where word spacing exceeds the threshold',
  debugLooseLinesColor: 'Highlight Color',
  debugLooseLinesColorTooltip: 'Fill color used to mark loose lines on the canvas',
  debugLooseLinesThreshold: 'Threshold',
  debugLooseLinesThresholdTooltip: 'Multiplier of the normal space width above which a justified line is considered loose',
  debugPageNegative: 'Page Negative',
  debugPageNegativeTooltip: 'Apply an inverse (negative) color filter to the page content on the canvas',
  bodyText: 'Body Text',
  bodyFont: 'Font',
  bodyFontTooltip: 'Font family for the body text',
  bodyFontSearch: 'Search fonts...',
  bodyFontNoResults: 'No fonts found',
  bodyFontSize: 'Text Size',
  bodyFontSizeTooltip: 'Font size for the body text',
  bodyLineHeight: 'Line Height',
  bodyLineHeightTooltip: 'Vertical spacing between lines of text',
  bodyParagraphSpacing: 'Paragraph Spacing',
  bodyParagraphSpacingTooltip: 'When enabled, insert a blank line (equal to line height) between consecutive paragraphs',
  bodyColor: 'Text Color',
  bodyColorTooltip: 'Color of the body text',
  bodyBoldColor: 'Bold Color',
  bodyBoldColorTooltip: 'Default color for bold text in body paragraphs. When unset, inherits the text color.',
  bodyItalicColor: 'Italic Color',
  bodyItalicColorTooltip: 'Default color for italic text in body paragraphs. When unset, inherits the text color.',
  bodyTextAlign: 'Text Alignment',
  bodyTextAlignTooltip: 'Horizontal alignment of body text paragraphs',
  bodyTextAlignLeft: 'Ragged Right',
  bodyTextAlignJustify: 'Justified',
  bodyHyphenation: 'Hyphenation',
  bodyHyphenationTooltip: 'Enable automatic hyphenation for justified text',
  bodyFontWeight: 'Font Weight',
  bodyFontWeightTooltip: 'Weight for normal body text (100-900)',
  bodyBoldFontWeight: 'Bold Weight',
  bodyBoldFontWeightTooltip: 'Weight for bold text in body paragraphs (100-900)',
  bodyHyphenationLocale: 'Language',
  bodyHyphenationLocaleTooltip: 'Language used for hyphenation rules',
  bodyFirstLineIndent: 'First Line Indent',
  bodyFirstLineIndentTooltip: 'Indent applied to the first line of each paragraph',
  bodyHangingIndent: 'Hanging Indent',
  bodyHangingIndentTooltip: 'When enabled, all lines except the first are indented (French indent)',
  bodyMaxWordSpacing: 'Max Word Spacing',
  bodyMaxWordSpacingTooltip: 'Maximum word spacing in justified text, as a multiplier of the normal space width',
  bodyMinWordSpacing: 'Min Word Spacing',
  bodyMinWordSpacingTooltip: 'Minimum word spacing in justified text, as a multiplier of the normal space width',
  bodyOptimalLineBreaking: 'Optimal Line Breaking',
  bodyOptimalLineBreakingTooltip: 'Use the Knuth-Plass algorithm for globally optimal line breaks instead of greedy first-fit',
  headings: 'Headings',
  headingsFont: 'Font',
  headingsFontTooltip: 'Default font family for all headings',
  headingsFontSearch: 'Search fonts...',
  headingsFontNoResults: 'No fonts found',
  headingsLineHeight: 'Line Height',
  headingsLineHeightTooltip: 'Default line height for all headings',
  headingsColor: 'Color',
  headingsColorTooltip: 'Default color for all headings',
  headingLevel: 'H',
  headingFontSize: 'Size',
  headingFontSizeTooltip: 'Font size for this heading level',
  headingLineHeight: 'Line Height',
  headingLineHeightTooltip: 'Override line height for this heading level',
  headingFont: 'Font',
  headingFontTooltip: 'Override font for this heading level',
  headingFontSearch: 'Search fonts...',
  headingFontNoResults: 'No fonts found',
  headingColor: 'Color',
  headingColorTooltip: 'Override color for this heading level',
  headingsFontWeight: 'Font Weight',
  headingsFontWeightTooltip: 'Default font weight for all headings (100-900)',
  headingsMarginTop: 'Margin Top',
  headingsMarginTopTooltip: 'Default space above headings (skipped at top of column)',
  headingsMarginBottom: 'Margin Bottom',
  headingsMarginBottomTooltip: 'Default minimum space below headings',
  headingsTextAlign: 'Text Alignment',
  headingsTextAlignTooltip: 'Horizontal alignment of headings',
  headingsTextAlignLeft: 'Ragged Right',
  headingsTextAlignJustify: 'Justified',
  headingFontWeight: 'Weight',
  headingFontWeightTooltip: 'Override font weight for this heading level',
  headingMarginTop: 'Margin Top',
  headingMarginTopTooltip: 'Space above this heading level (skipped at top of column)',
  headingMarginBottom: 'Margin Bottom',
  headingMarginBottomTooltip: 'Minimum space below this heading level',
  headingNumberingTemplate: 'Numbering',
  headingNumberingTemplateTooltip: 'Template for this level\'s number prefix. Use {N} for the counter at level N, {N:style} to pick a numeral style (1, 01, A, a, I, i). Examples: "{1}.", "{1}.{2}", "{2:A}.{3}". Empty = no numbering.',
  headingNumberingTemplatePlaceholder: 'e.g. {1}.{2}',
  headingItalic: 'Italic',
  headingItalicTooltip: 'Render this heading level in italic style',
  unorderedLists: 'Unordered Lists',
  unorderedListsFont: 'Bullet Font',
  unorderedListsFontTooltip: 'Default font family used to render list bullets (inherits from body text when unset)',
  unorderedListsFontSearch: 'Search fonts...',
  unorderedListsFontNoResults: 'No fonts found',
  unorderedListsColor: 'Bullet Color',
  unorderedListsColorTooltip: 'Default color for list bullets (inherits from body text when unset)',
  unorderedListsFontWeight: 'Bullet Weight',
  unorderedListsFontWeightTooltip: 'Default font weight for list bullets (100-900)',
  unorderedListsItalic: 'Italic',
  unorderedListsItalicTooltip: 'Render list bullets in italic',
  unorderedListsBulletChar: 'Bullet Character',
  unorderedListsBulletCharTooltip: 'Glyph used as the default bullet for every depth level',
  unorderedListsBulletCharPlaceholder: 'e.g. •, —, ✓',
  unorderedListsBulletFontSize: 'Bullet Size',
  unorderedListsBulletFontSizeTooltip: 'Font size for the bullet glyph (em is relative to body text)',
  unorderedListsGap: 'Bullet Gap',
  unorderedListsGapTooltip: 'Horizontal distance between the bullet and the start of the item text',
  unorderedListsIndent: 'Base Indent',
  unorderedListsIndentTooltip: 'Base indent per depth level — level N defaults to this value × N. Set to 0 to pin bullets to the column edge.',
  unorderedListsBulletVerticalOffset: 'Vertical Offset',
  unorderedListsBulletVerticalOffsetTooltip: 'Fine-tune bullet vertical position. Negative values raise the bullet, positive values lower it. Useful when a custom glyph does not sit exactly centered on the text.',
  unorderedListsMarginTop: 'Margin Top',
  unorderedListsMarginTopTooltip: 'Space before the first item of a list',
  unorderedListsMarginBottom: 'Margin Bottom',
  unorderedListsMarginBottomTooltip: 'Space after the last item of a list',
  unorderedListsItemSpacing: 'Item Spacing',
  unorderedListsItemSpacingTooltip: 'Extra vertical space between consecutive list items',
  unorderedListsHangingIndent: 'Hanging Indent',
  unorderedListsHangingIndentTooltip: 'When enabled, wrapped lines align to the text start instead of the bullet column',
  unorderedListLevel: 'L',
  unorderedListLevelBulletChar: 'Character',
  unorderedListLevelBulletCharTooltip: 'Override the bullet character for this depth level',
  unorderedListLevelFont: 'Font',
  unorderedListLevelFontTooltip: 'Override the bullet font for this depth level',
  unorderedListLevelFontSize: 'Size',
  unorderedListLevelFontSizeTooltip: 'Override the bullet font size for this depth level',
  unorderedListLevelColor: 'Color',
  unorderedListLevelColorTooltip: 'Override the bullet color for this depth level',
  unorderedListLevelFontWeight: 'Weight',
  unorderedListLevelFontWeightTooltip: 'Override the bullet font weight for this depth level',
  unorderedListLevelItalic: 'Italic',
  unorderedListLevelItalicTooltip: 'Render this depth level bullet in italic',
  unorderedListLevelIndent: 'Indent',
  unorderedListLevelIndentTooltip: 'Horizontal indent from the column edge to the bullet for this depth level',
  unorderedListLevelVerticalOffset: 'Vertical Offset',
  unorderedListLevelVerticalOffsetTooltip: 'Override vertical nudge for this depth level. Negative = up, positive = down.',
  taskLists: 'Task Lists',
  taskCheckboxChar: 'Unchecked Character',
  taskCheckboxCharTooltip: 'Glyph used as the checkbox for pending task items (`- [ ]`).',
  taskCheckboxCharPlaceholder: 'e.g. ☐, ☒, [ ]',
  taskCheckedChar: 'Checked Character',
  taskCheckedCharTooltip: 'Glyph used as the checkbox for completed task items (`- [x]`).',
  taskCheckedCharPlaceholder: 'e.g. ☑, ✓, [x]',
  taskCompletedStrikethrough: 'Strikethrough Completed',
  taskCompletedStrikethroughTooltip: 'Draw a line through the text of completed task items.',
  taskCompletedColor: 'Completed Color',
  taskCompletedColorTooltip: 'Text color for completed task items. When unset, the body color is used.',
  orderedLists: 'Ordered Lists',
  orderedListsFont: 'Number Font',
  orderedListsFontTooltip: 'Default font family used to render ordered list numbers (inherits from body text when unset).',
  orderedListsFontSearch: 'Search fonts...',
  orderedListsFontNoResults: 'No fonts found',
  orderedListsColor: 'Number Color',
  orderedListsColorTooltip: 'Default color for ordered list numbers (inherits from body text when unset).',
  orderedListsFontWeight: 'Number Weight',
  orderedListsFontWeightTooltip: 'Default font weight for ordered list numbers (100-900).',
  orderedListsItalic: 'Italic',
  orderedListsItalicTooltip: 'Render ordered list numbers in italic.',
  orderedListsNumberFormat: 'Number Format',
  orderedListsNumberFormatTooltip: 'Default numbering format for every depth level.',
  orderedListsNumberFormatArabic: 'Arabic (1, 2, 3)',
  orderedListsNumberFormatLowerAlpha: 'Lower Alpha (a, b, c)',
  orderedListsNumberFormatUpperAlpha: 'Upper Alpha (A, B, C)',
  orderedListsNumberFormatLowerRoman: 'Lower Roman (i, ii, iii)',
  orderedListsNumberFormatUpperRoman: 'Upper Roman (I, II, III)',
  orderedListsSeparator: 'Separator',
  orderedListsSeparatorTooltip: 'Character(s) appended after the number (e.g. `.`, `)`, `:`).',
  orderedListsSeparatorPlaceholder: 'e.g. ., ), :',
  orderedListsNumberFontSize: 'Number Size',
  orderedListsNumberFontSizeTooltip: 'Font size for the numbers (em is relative to body text).',
  orderedListsGap: 'Number Gap',
  orderedListsGapTooltip: 'Horizontal distance between the number+separator and the start of the item text.',
  orderedListsIndent: 'Base Indent',
  orderedListsIndentTooltip: 'Base indent for level 1. Deeper levels cascade from their parent unless overridden.',
  orderedListsNumberVerticalOffset: 'Vertical Offset',
  orderedListsNumberVerticalOffsetTooltip: 'Fine-tune number vertical position. Negative values raise, positive values lower.',
  orderedListsMarginTop: 'Margin Top',
  orderedListsMarginTopTooltip: 'Space before the first item of a list.',
  orderedListsMarginBottom: 'Margin Bottom',
  orderedListsMarginBottomTooltip: 'Space after the last item of a list.',
  orderedListsItemSpacing: 'Item Spacing',
  orderedListsItemSpacingTooltip: 'Extra vertical space between consecutive list items.',
  orderedListsHangingIndent: 'Hanging Indent',
  orderedListsHangingIndentTooltip: 'When enabled, wrapped lines align to the text start instead of the number column.',
  orderedListLevel: 'L',
  orderedListLevelNumberFormat: 'Format',
  orderedListLevelNumberFormatTooltip: 'Override the numbering format for this depth level.',
  orderedListLevelSeparator: 'Separator',
  orderedListLevelSeparatorTooltip: 'Override the separator for this depth level.',
  orderedListLevelFont: 'Font',
  orderedListLevelFontTooltip: 'Override the number font for this depth level.',
  orderedListLevelFontSize: 'Size',
  orderedListLevelFontSizeTooltip: 'Override the number font size for this depth level.',
  orderedListLevelColor: 'Color',
  orderedListLevelColorTooltip: 'Override the number color for this depth level.',
  orderedListLevelFontWeight: 'Weight',
  orderedListLevelFontWeightTooltip: 'Override the number font weight for this depth level.',
  orderedListLevelItalic: 'Italic',
  orderedListLevelItalicTooltip: 'Render this depth level number in italic.',
  orderedListLevelIndent: 'Indent',
  orderedListLevelIndentTooltip: 'Horizontal indent from the column edge to the number column for this depth level.',
  orderedListLevelVerticalOffset: 'Vertical Offset',
  orderedListLevelVerticalOffsetTooltip: 'Override vertical nudge for this depth level. Negative = up, positive = down.',
  layout: 'Layout',
  layoutType: 'Layout Type',
  layoutTypeTooltip: 'Column layout mode for the content area',
  layoutSingle: 'Single Column',
  layoutDouble: 'Double Column',
  layoutOneAndHalf: 'Column and a Half',
  gutterWidth: 'Gutter Width',
  gutterWidthTooltip: 'Space between columns',
  sideColumnPercent: 'Side Column',
  sideColumnPercentTooltip: 'Width of the side column as a percentage of the content area',
  columnRule: 'Column Rule',
  columnRuleTooltip: 'Show a vertical line between columns',
  columnRuleColor: 'Rule Color',
  columnRuleColorTooltip: 'Color of the column rule line',
  columnRuleLineWidth: 'Rule Width',
  columnRuleLineWidthTooltip: 'Thickness of the column rule line',
  zoomIn: 'Zoom In',
  zoomOut: 'Zoom Out',
  fitWidth: 'Fit to Page Width',
  fitHeight: 'Fit to Page Height',
  singlePage: 'Single Page',
  doublePageSpread: 'Double-Page Spread',
  canvasToolbar: 'Canvas toolbar',
  bold: 'Bold',
  italic: 'Italic',
  heading: 'Heading',
  link: 'Link',
  code: 'Code',
  blockquote: 'Blockquote',
  orderedList: 'Ordered List',
  unorderedList: 'Unordered List',
  undo: 'Undo',
  redo: 'Redo',
  save: 'Save',
  load: 'Load',
  exportFile: 'Export',
  importFile: 'Import',
  reset: 'Reset',
  resetConfigConfirm: 'Reset all configuration to defaults?',
  resetSectionConfirm: 'Reset this section to defaults?',
  resetMarkdownConfirm: 'Replace content with the default example?',
  colorPalette: 'Color palette',
  colorPaletteTooltip: 'Named colors reusable across all color fields. Changing an entry updates every reference.',
  colorPaletteEntryName: 'Name',
  colorPaletteAdd: 'Add color',
  colorPaletteRemove: 'Remove',
  colorPaletteNewEntry: 'New color',
  colorPaletteLink: 'Link to palette',
  colorPaletteUnlink: 'Unlink',
  colorPaletteNone: 'No palette entries yet',
  colorPaletteEditName: 'Edit name',
  colorPaletteDeleteConfirm: 'Delete this color?',
  colorPaletteDeleteInUse: 'Used by:',
  colorPaletteDeleteInUseNote: 'These properties will keep the color but lose the link.',
};
