"""Editorial content of the `espana-en-mapas` showcase preset: book strings
and the five eras (parts) of the Atlas Nacional de España history chapter,
in Spanish and English. The texts and maps are the IGN's own (CC BY 4.0
ign.es); only the wording here was written for the preset.
"""
from __future__ import annotations

BOOK = {
    "es": {
        "title": "España en mapas",
        "subtitle": "Referencias históricas",
        "series": "Atlas Nacional de España · Una síntesis geográfica",
        "publisher": "Instituto Geográfico Nacional · Centro Nacional de Información Geográfica",
        "intro": "Sobre esta edición",
        "contents": "Índice",
        "credits": "Créditos y licencia",
        "chapter_label": "{partTitle}",
        "part_label": "Sección {numberRoman}",
        "map": ("Mapa", "Mapas", "mapa"),
        "figure": ("Figura", "Figuras", "figura"),
        "map_note": "Atlas Nacional de España (ANE), Instituto Geográfico Nacional · CC BY 4.0 ign.es",
        "photo_note": "Fotografía: Atlas Nacional de España (ANE) · CC BY 4.0 ign.es",
        "source_line": "Texto del capítulo «Referencias históricas» de *España en mapas. Una síntesis geográfica* (Atlas Nacional de España, IGN, 2023), reproducido bajo la licencia CC BY 4.0 ign.es.",
        "intro_text": [
            "El Atlas Nacional de España es una obra del Instituto Geográfico Nacional que, desde 1955, reúne en mapas, gráficos y textos una descripción completa del territorio español. Su edición más reciente, *España en mapas. Una síntesis geográfica*, se publica por capítulos en formato digital bajo una licencia abierta, Creative Commons Atribución 4.0, que permite reproducir y reutilizar tanto los textos como la cartografía citando la fuente.",
            "Esta edición de muestra recompone el capítulo de referencias históricas, un recorrido desde el Paleolítico hasta la democracia, con los mapas que el IGN dibujó para cada época. La composición es nueva: página de 260 × 365 mm a dos columnas, mapas a página o a columna con sus pies, portadillas de sección con paleta propia e índice generado por Postext. Los textos y los mapas son los del atlas, sin cambios.",
        ],
    },
    "en": {
        "title": "Spain in maps",
        "subtitle": "Historical overview",
        "series": "National Atlas of Spain · A geographical synthesis",
        "publisher": "Instituto Geográfico Nacional · Centro Nacional de Información Geográfica",
        "intro": "About this edition",
        "contents": "Contents",
        "credits": "Credits and licence",
        "chapter_label": "{partTitle}",
        "part_label": "Section {numberRoman}",
        "map": ("Map", "Maps", "map"),
        "figure": ("Figure", "Figures", "figure"),
        "map_note": "National Atlas of Spain (ANE), Instituto Geográfico Nacional · CC BY 4.0 ign.es",
        "photo_note": "Photograph: National Atlas of Spain (ANE) · CC BY 4.0 ign.es",
        "source_line": "Text from the chapter “Historical overview” of *Spain in maps. A geographical synthesis* (National Atlas of Spain, IGN, 2024), reproduced under the CC BY 4.0 ign.es licence.",
        "intro_text": [
            "The National Atlas of Spain is a work of the Instituto Geográfico Nacional that, since 1955, has gathered a complete description of the Spanish territory in maps, charts and texts. Its latest edition, *Spain in maps. A geographical synthesis*, is published chapter by chapter in digital form under an open licence, Creative Commons Attribution 4.0, which allows both texts and maps to be reproduced and reused with credit.",
            "This sample edition re-sets the chapter of historical references, a journey from the Paleolithic to democracy, with the maps the IGN drew for each era. The setting is new: a 260 × 365 mm page in two columns, page-wide and column maps with their captions, section openers with their own palette and a contents page generated by Postext. Texts and maps are the atlas's own, unchanged.",
        ],
    },
}

# The eras, in order: Spanish running head → number, band colour, English name.
PARTS = [
    {"es": "Prehistoria", "en": "Prehistory", "number": "I", "band": "#8a6d3b"},
    {"es": "Edad Antigua", "en": "Ancient Age", "number": "II", "band": "#a63d3d"},
    {"es": "Edad Media", "en": "Middle Ages", "number": "III", "band": "#3f6f9f"},
    {"es": "Edad Moderna", "en": "Modern Age", "number": "IV", "band": "#4c8a55"},
    {"es": "Edad Contemporánea", "en": "Contemporary Age", "number": "V", "band": "#6b4c9a"},
]

# Pages of the chapter PDFs that hold the body (front matter and indices
# excluded), and whether paragraphs carry a first-line indent.
PAGES = {"es": (6, 39), "en": (6, 39)}
INDENTS = {"es": True, "en": False}

# Words the map titles keep in upper case when title-cased.
KEEP_UPPER = {"II", "III", "IV", "VI", "VII", "VIII", "IX", "XI", "XII", "XIII", "XIV", "XV", "XVI", "XVII", "XVIII", "XIX", "XX", "XXI", "UE", "EU", "OTAN", "NATO", "ONU", "UN", "ETA", "PSOE", "UCD", "PP", "RENFE", "a.C.", "d.C.", "BC", "AD"}
SMALL_WORDS = {"es": {"de", "del", "la", "las", "el", "los", "y", "e", "en", "a", "al", "con", "por", "para", "o", "u", "durante", "entre", "sobre", "según", "hasta"}, "en": {"of", "the", "and", "in", "on", "at", "to", "a", "an", "by", "for", "with", "from", "during", "between", "or", "under"}}

COVER_BLURB = {
    "es": "Edición de muestra compuesta con Postext a partir del capítulo «Referencias históricas» del Atlas Nacional de España (IGN, 2023), publicado bajo la licencia CC BY 4.0 ign.es.",
    "en": "A sample edition set with Postext from the chapter “Historical overview” of the National Atlas of Spain (IGN, 2024), published under the CC BY 4.0 ign.es licence.",
}

CREDITS = {
    "es": [
        "**Textos y mapas.** *España en mapas. Una síntesis geográfica*, capítulo de Referencias históricas (2023) y su edición inglesa *Historical overview* (2024), Atlas Nacional de España, Instituto Geográfico Nacional y Centro Nacional de Información Geográfica. Licencia Creative Commons Atribución 4.0 Internacional; atribución exigida: «CC BY 4.0 ign.es». Los mapas se han rasterizado a partir del PDF original; cada uno conserva su compilación científica y su línea de fuente.",
        "**Cambios respecto al original.** Se han omitido los índices, la bibliografía y la relación de participantes; los mapas se numeran de forma correlativa y sus títulos se han pasado a caja baja para los pies. El resto del texto se reproduce sin modificaciones.",
        "**Tipografía.** Source Sans 3, de Paul D. Hunt (Adobe); Archivo, de Omnibus-Type. Ambas familias se distribuyen bajo la SIL Open Font License 1.1.",
        "**Composición.** Página de 260 × 365 mm a dos columnas, mapas a página completa y a columna, portadillas de sección con paleta propia, titulillos, folios e índice generados por Postext.",
    ],
    "en": [
        "**Texts and maps.** *Spain in maps. A geographical synthesis*, chapter Historical overview (2024) and its Spanish original *Referencias históricas* (2023), National Atlas of Spain, Instituto Geográfico Nacional and Centro Nacional de Información Geográfica. Creative Commons Attribution 4.0 International licence; required attribution: “CC BY 4.0 ign.es”. The maps were rasterised from the original PDF; each keeps its scientific compilation and source line.",
        "**Changes from the original.** The indices, bibliography and list of participants were left out; maps are numbered consecutively and their titles set in lower case for the captions. The rest of the text is reproduced unchanged.",
        "**Type.** Source Sans 3 by Paul D. Hunt (Adobe); Archivo by Omnibus-Type. Both families are distributed under the SIL Open Font License 1.1.",
        "**Setting.** A 260 × 365 mm two-column page, page-wide and column maps, section openers with their own palette, running heads, folios and a contents page generated by Postext.",
    ],
}
