// Embed the bundled CSL styles and locales (csl/) as string modules, so the
// package needs no file system or network at run time — in a browser worker
// as in Node. Run after adding or updating a file in csl/.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const out = path.join(root, 'src', 'generated');
fs.mkdirSync(out, { recursive: true });

function embed(dir, ext, file, name) {
  const entries = fs.readdirSync(path.join(root, 'csl', dir)).filter((f) => f.endsWith(ext)).sort();
  const lines = [
    '// Generated by scripts/embed-csl.mjs from csl/' + dir + ' — do not edit.',
    '// CSL styles and locales: Citation Style Language project, CC BY-SA 3.0.',
    `export const ${name}: Readonly<Record<string, string>> = {`,
  ];
  for (const f of entries) {
    const key = f.slice(0, -ext.length).replace(/^locales-/, '');
    const xml = fs.readFileSync(path.join(root, 'csl', dir, f), 'utf8');
    lines.push(`  ${JSON.stringify(key)}: ${JSON.stringify(xml)},`);
  }
  lines.push('};', '');
  fs.writeFileSync(path.join(out, file), lines.join('\n'));
  return entries.length;
}

const s = embed('styles', '.csl', 'styles.ts', 'STYLES');
const l = embed('locales', '.xml', 'locales.ts', 'LOCALES');
console.log(`embedded ${s} styles, ${l} locales`);
