#!/usr/bin/env python3
"""Helpers and commands to assemble a Postext project (a *preset bundle*).

A bundle is a folder the Postext sandbox can open:

    <project>/
      preset.json            manifest (generated by build_preset.py; don't hand-edit)
      build_preset.py        YOUR generator: measured design constants -> config
      chapters/<lang>/NN-slug.md
      resources/             figures (svg/png/jpg/webp/gif) + optional .pdf print masters
      fonts/                 ttf / otf / woff2 single faces
      resources.json         resource list (figures, tables) read by build_preset.py
      thumbnail.jpg          optional

Commands:
  preset_kit.py init <project> --id my-book --name "My book" --lang es [--lang en]
      Create the folders and a build_preset.py to fill in.
  preset_kit.py pack <project> [--out my-book.postext]
      Zip the bundle as a .postext file (Sandbox > Projects > Import .postext).
  preset_kit.py index <presets-root>
      Write <presets-root>/index.json listing every preset.json below it (for
      POSTEXT_PRIVATE_PRESETS_DIR or a static host).
  preset_kit.py fonts <project>
      Print the `fonts` entries for the faces in <project>/fonts (family, weight,
      style read from the font files; needs fontTools, else guessed from names).

Library (import from build_preset.py):
  mm(12) / pt(9.5) / em(1.2)          Dimension objects
  color("#1d3557", "main-color")       ColorValue linked to a palette entry
  palette({"main-color": ("Main", "#1d3557"), ...})
  text_el(...), rule_el(...), box_el(...), image_el(...)   design elements
  place(anchor, edge, x=0, y=0, width=None, height=None)   ElementPlacement
  bitmap(id, file, caption, ...), svg(id, file, ...), table(id, rows, ...)
  chapters_from_dir(project, lang)     [{title, file}] from chapters/<lang>/*.md
  font_families(project)               `fonts` entries from fonts/
  write_manifest(project, manifest)    writes preset.json (+ fingerprint.json)
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import zipfile
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# primitives
# ---------------------------------------------------------------------------


def dim(value: float, unit: str) -> dict:
    return {"value": round(float(value), 4), "unit": unit}


def mm(v: float) -> dict:
    return dim(v, "mm")


def pt(v: float) -> dict:
    return dim(v, "pt")


def em(v: float) -> dict:
    """Only where the reference allows em (line heights, margins of headings,
    lists, callouts…). Geometry and font sizes must be absolute (mm/pt)."""
    return dim(v, "em")


def color(hex_: str, palette_id: str | None = None, model: str = "hex") -> dict:
    c = {"hex": hex_.lower(), "model": model}
    if palette_id:
        c["paletteId"] = palette_id
    return c


def palette(entries: dict[str, tuple[str, str]]) -> list[dict]:
    """{"main-color": ("Main", "#1d3557")} -> colorPalette. Include `main-color`:
    every built-in accent (headings, bold, bullets, callouts…) points at it."""
    return [{"id": k, "name": name, "value": {"hex": hx.lower(), "model": "hex"}} for k, (name, hx) in entries.items()]


def place(anchor: str = "page", edge: str = "top-left", x: float = 0, y: float = 0,
          width: Any = None, height: Any = None, max_width: Any = None, unit: str = "mm") -> dict:
    """ElementPlacement. anchor: 'container' | 'page' | 'bleed' | '#elementId'.
    Offsets are screen directions (+x right, +y down) in `unit`; a right/bottom
    anchored element needs negative offsets to move inwards."""
    p: dict = {"anchor": {"to": anchor, "edge": edge}}
    off = {}
    if x:
        off["x"] = dim(x, unit)
    if y:
        off["y"] = dim(y, unit)
    if off:
        p["offset"] = off
    size = {}
    for k, v in (("width", width), ("height", height), ("maxWidth", max_width)):
        if v is None:
            continue
        size[k] = v if isinstance(v, (str, dict)) else dim(v, unit)
    if size:
        p["size"] = size
    return p


def text_el(id_: str, content: str, placement: dict, *, font: str, size: float, weight: int = 400,
            italic: bool = False, fill: dict | None = None, align: str = "left", valign: str = "top",
            overflow: str = "ellipsis-end", line_height: float | None = None, uppercase: bool = False,
            letter_spacing: float | None = None, parity: str | None = None, pages: str | None = None,
            **extra) -> dict:
    """Design text element. `content` is a template: {pageNumber}, {chapterTitle},
    {chapterNumber}, {partTitle}, {partNumber}, {title}, {titleText}, {number},
    {attr.<key>}… Set every typographic field: element defaults are not the
    body's."""
    el = {"kind": "text", "id": id_, "placement": placement, "content": content,
          "fontFamily": font, "fontSize": pt(size), "fontWeight": weight, "italic": italic,
          "color": fill or color("#000000"), "align": align, "verticalAlign": valign, "overflow": overflow}
    if line_height:
        el["lineHeight"] = line_height
    if uppercase:
        el["textTransform"] = "uppercase"
    if letter_spacing:
        el["letterSpacing"] = em(letter_spacing)
    if parity:
        el["parity"] = parity
    if pages:
        el["pages"] = pages
    el.update(extra)
    return el


def rule_el(id_: str, placement: dict, *, direction: str = "horizontal", fill: dict | None = None,
            thickness: float = 0.5, parity: str | None = None, pages: str | None = None) -> dict:
    el = {"kind": "rule", "id": id_, "placement": placement, "direction": direction,
          "color": fill or color("#000000"), "thickness": pt(thickness)}
    if parity:
        el["parity"] = parity
    if pages:
        el["pages"] = pages
    return el


def box_el(id_: str, placement: dict, *, fill: dict | None = None, border: dict | None = None,
           border_width: float | None = None, radius: float | None = None,
           parity: str | None = None, pages: str | None = None) -> dict:
    style: dict = {}
    if fill:
        style["backgroundColor"] = fill
    if border:
        style["borderColor"] = border
    if border_width:
        style["borderWidth"] = pt(border_width)
    if radius:
        style["borderRadius"] = mm(radius)
    el = {"kind": "box", "id": id_, "placement": placement, "style": style}
    if parity:
        el["parity"] = parity
    if pages:
        el["pages"] = pages
    return el


def image_el(id_: str, resource_id: str, placement: dict, *, parity: str | None = None,
             pages: str | None = None) -> dict:
    el = {"kind": "image", "id": id_, "placement": placement, "resourceId": resource_id}
    if parity:
        el["parity"] = parity
    if pages:
        el["pages"] = pages
    return el


# ---------------------------------------------------------------------------
# resources
# ---------------------------------------------------------------------------


def image_size(path: Path) -> tuple[int, int] | None:
    try:
        from PIL import Image  # type: ignore

        with Image.open(path) as im:
            return im.width, im.height
    except Exception:
        pass
    data = path.read_bytes()[:64 * 1024]
    if data[:8] == b"\x89PNG\r\n\x1a\n":
        return int.from_bytes(data[16:20], "big"), int.from_bytes(data[20:24], "big")
    if data[:2] == b"\xff\xd8":
        i = 2
        while i < len(data) - 9:
            if data[i] != 0xFF:
                i += 1
                continue
            marker = data[i + 1]
            length = int.from_bytes(data[i + 2:i + 4], "big")
            if marker in (0xC0, 0xC1, 0xC2):
                return int.from_bytes(data[i + 7:i + 9], "big"), int.from_bytes(data[i + 5:i + 7], "big")
            i += 2 + length
    return None


def svg_size(path: Path) -> tuple[float, float] | None:
    head = path.read_text(encoding="utf-8", errors="ignore")[:4000]

    def num(attr: str) -> float | None:
        m = re.search(rf'\s{attr}="([\d.]+)(pt|px)?"', head)
        return float(m.group(1)) if m else None

    w, h = num("width"), num("height")
    if w and h:
        return w, h
    m = re.search(r'viewBox="\s*[-\d.]+[\s,]+[-\d.]+[\s,]+([\d.]+)[\s,]+([\d.]+)', head)
    return (float(m.group(1)), float(m.group(2))) if m else None


def _placement(position: str | None, span: str | None, **more) -> dict | None:
    p = {k: v for k, v in (("position", position), ("span", span)) if v}
    p.update({k: v for k, v in more.items() if v is not None})
    return p or None


def bitmap(project: Path | str, id_: str, file: str, caption: str = "", *, type_id: str = "figure",
           alt: str | None = None, note: str | None = None, position: str | None = None,
           span: str | None = None, **placement) -> dict:
    """A bitmap resource with its pixel size (Node renderers cannot decode it)."""
    size = image_size(Path(project) / file)
    r = {"id": id_, "typeId": type_id, "kind": "bitmap", "file": file, "caption": caption,
         "altText": alt if alt is not None else re.sub(r"[*_^~]", "", caption)}
    if size:
        r["width"], r["height"] = size
    if note:
        r["note"] = note
    pl = _placement(position, span, **placement)
    if pl:
        r["placement"] = pl
    return r


def svg(project: Path | str, id_: str, file: str, caption: str = "", *, type_id: str = "figure",
        pdf_file: str | None = None, alt: str | None = None, note: str | None = None,
        position: str | None = None, span: str | None = None, **placement) -> dict:
    size = svg_size(Path(project) / file)
    r = {"id": id_, "typeId": type_id, "kind": "svg", "file": file, "caption": caption,
         "altText": alt if alt is not None else re.sub(r"[*_^~]", "", caption)}
    if size:
        r["width"], r["height"] = round(size[0], 2), round(size[1], 2)
    if pdf_file:
        r["pdfFile"] = pdf_file
    if note:
        r["note"] = note
    pl = _placement(position, span, **placement)
    if pl:
        r["placement"] = pl
    return r


def table(id_: str, rows: list[list[Any]], caption: str = "", *, header_rows: int = 1,
          column_widths: list[float] | None = None, style_id: str | None = None,
          type_id: str = "table", note: str | None = None, position: str | None = None,
          span: str | None = None, **placement) -> dict:
    """rows: lists of cells; a cell is a string or a TableCell dict. Header rows
    get isHeader. Merged cells: give the primary cell colSpan/rowSpan and keep a
    {"content": "", "hiddenBy": {"row": r, "col": c}} in every slot it covers."""
    model_rows = []
    for r_i, row in enumerate(rows):
        cells = []
        for cell in row:
            c = {"content": cell} if isinstance(cell, str) else dict(cell)
            if r_i < header_rows and "hiddenBy" not in c:
                c.setdefault("isHeader", True)
            cells.append(c)
        model_rows.append(cells)
    widths = {len(r) for r in model_rows}
    if len(widths) > 1:
        raise ValueError(f"table {id_}: every row needs one cell per column (use hiddenBy for merged slots); got widths {sorted(widths)}")
    model: dict = {"rows": model_rows}
    if header_rows:
        model["headerRowCount"] = header_rows
    if column_widths:
        model["columnWidths"] = column_widths
    t = {"id": id_, "typeId": type_id, "kind": "table", "caption": caption, "table": {"model": model}}
    if style_id:
        t["table"]["styleId"] = style_id
    if note:
        t["note"] = note
    pl = _placement(position, span, **placement)
    if pl:
        t["placement"] = pl
    return t


# ---------------------------------------------------------------------------
# chapters, fonts, manifest
# ---------------------------------------------------------------------------


def chapter_title(md: str) -> str:
    fm = re.match(r"^---\r?\n([\s\S]*?)\r?\n---", md)
    body = md[fm.end():] if fm else md
    m = re.search(r"^#\s+(.+)$", body, re.M)
    if m:
        t = re.sub(r"\s+\{[^{}]*\}\s*$", "", m.group(1))
        return re.sub(r"\s*\\\\\s*", " ", t).strip()
    if fm:
        t = re.search(r'^title:\s*"?(.+?)"?\s*$', fm.group(1), re.M)
        if t:
            return t.group(1)
    return ""


def chapters_from_dir(project: Path | str, lang: str) -> list[dict]:
    """Every chapters/<lang>/*.md in name order (01-…, 02-…)."""
    project = Path(project)
    out = []
    for f in sorted((project / "chapters" / lang).glob("*.md")):
        title = chapter_title(f.read_text(encoding="utf-8")) or f.stem
        out.append({"title": title, "file": f"chapters/{lang}/{f.name}"})
    return out


def font_families(project: Path | str, redistributable: dict[str, bool] | None = None) -> list[dict]:
    """`fonts` entries from project/fonts (ttf/otf/woff2). Family, weight and style
    come from the font tables (fontTools), else from 'Family-BoldItalic' names."""
    project = Path(project)
    fams: dict[str, list[dict]] = {}
    for f in sorted((project / "fonts").glob("*")):
        if f.suffix.lower() not in (".ttf", ".otf", ".woff2"):
            continue
        fam, weight, style = _font_meta(f)
        fams.setdefault(fam, []).append({"weight": weight, "style": style, "file": f"fonts/{f.name}"})
    out = []
    for name, variants in fams.items():
        entry: dict = {"name": name, "variants": sorted(variants, key=lambda v: (v["style"], v["weight"]))}
        if redistributable and redistributable.get(name) is False:
            entry["redistributable"] = False
        out.append(entry)
    return out


_WEIGHTS = {"thin": 100, "extralight": 200, "ultralight": 200, "light": 300, "regular": 400, "book": 400,
            "normal": 400, "medium": 500, "semibold": 600, "demibold": 600, "demi": 600, "bold": 700,
            "extrabold": 800, "ultrabold": 800, "black": 900, "heavy": 900}


def _font_meta(path: Path) -> tuple[str, int, str]:
    try:
        from fontTools.ttLib import TTFont  # type: ignore

        f = TTFont(str(path), lazy=True, fontNumber=0)
        name = f["name"]
        fam = name.getDebugName(16) or name.getDebugName(1) or path.stem
        weight = f["OS/2"].usWeightClass if "OS/2" in f else 400
        italic = bool(f["OS/2"].fsSelection & 1) if "OS/2" in f else False
        if "head" in f and f["head"].macStyle & 2:
            italic = True
        return fam, int(weight), "italic" if italic else "normal"
    except Exception:
        stem = path.stem
        fam, _, sub = stem.partition("-")
        low = sub.lower()
        italic = "italic" in low or "oblique" in low
        low = low.replace("italic", "").replace("oblique", "")
        weight = _WEIGHTS.get(low or "regular", 400)
        return re.sub(r"(?<=[a-z])(?=[A-Z])", " ", fam), weight, "italic" if italic else "normal"


def fingerprint(project: Path | str) -> str:
    project = Path(project)
    h = hashlib.sha1()
    for p in sorted(project.rglob("*")):
        if p.is_file() and p.name not in ("fingerprint.json",) and not p.name.startswith("."):
            st = p.stat()
            h.update(f"{p.relative_to(project)}:{st.st_size}:{int(st.st_mtime)}\n".encode())
    return h.hexdigest()


def write_manifest(project: Path | str, manifest: dict) -> Path:
    """Write preset.json (v2) after checking that every referenced file exists,
    then fingerprint.json (lets the sandbox notice edits)."""
    project = Path(project)
    manifest.setdefault("version", 2)
    missing = []
    chapters = manifest.get("chapters", {})
    specs = chapters if isinstance(chapters, list) else [c for v in chapters.values() for c in v]
    for c in specs:
        if not (project / c["file"]).exists():
            missing.append(c["file"])
    for r in manifest.get("resources", []):
        for k in ("file", "pdfFile"):
            if r.get(k) and not (project / r[k]).exists():
                missing.append(r[k])
    for f in manifest.get("fonts", []):
        for v in f.get("variants", []):
            if not (project / v["file"]).exists():
                missing.append(v["file"])
    if manifest.get("config", {}).get("customFonts"):
        raise ValueError("config.customFonts must not be written: fonts come from the `fonts` array")
    if missing:
        raise FileNotFoundError("missing files: " + ", ".join(missing))
    out = project / "preset.json"
    out.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    (project / "fingerprint.json").write_text(json.dumps({"fingerprint": fingerprint(project)}) + "\n", encoding="utf-8")
    return out


# ---------------------------------------------------------------------------
# commands
# ---------------------------------------------------------------------------

TEMPLATE = '''#!/usr/bin/env python3
"""Generator for the {name} Postext project. Measured design -> preset.json.

Keep every measurement here as a constant with a comment saying where it was
measured ("p. 12: text block 128 mm wide, 48 lines of 12 pt"). Re-run after
every change and reload the project in the sandbox.
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, {kit_dir!r})  # folder holding preset_kit.py
from preset_kit import (  # noqa: E402
    bitmap, box_el, chapters_from_dir, color, font_families, mm, palette, place, pt,
    rule_el, svg, table, text_el, write_manifest,
)

ID = {id!r}
NAME = {name!r}
LANGS = {langs!r}

# ---- measured geometry (mm, from the trim) ---------------------------------
PAGE_W, PAGE_H = 170, 240
MARGIN_TOP, MARGIN_BOTTOM, MARGIN_INNER, MARGIN_OUTER = 20, 22, 18, 15
GUTTER = 5
BODY_FONT, BODY_SIZE, LEADING = "Body Face", 9.5, 12.5   # pt; LEADING = baseline grid

PALETTE = palette({{
    "main-color": ("Accent", "#1d3557"),   # every built-in accent points here
    "ink": ("Ink", "#1a1a1a"),
}})
ACCENT = color("#1d3557", "main-color")
INK = color("#1a1a1a", "ink")


def config(lang: str) -> dict:
    return {{
        "locale": {{"es": "es", "en": "en-us"}}.get(lang, lang),
        "page": {{"sizePreset": "custom", "width": mm(PAGE_W), "height": mm(PAGE_H),
                  "margins": {{"top": mm(MARGIN_TOP), "bottom": mm(MARGIN_BOTTOM),
                              "left": mm(MARGIN_INNER), "right": mm(MARGIN_OUTER), "mirror": True}}}},
        "layout": {{"layoutType": "double", "gutterWidth": mm(GUTTER)}},
        "colorPalette": PALETTE,
        "bodyText": {{"fontFamily": BODY_FONT, "fontSize": pt(BODY_SIZE), "lineHeight": pt(LEADING),
                      "color": INK, "boldColor": INK, "italicColor": INK, "textAlign": "justify",
                      "hyphenation": {{"enabled": True, "locale": {{"es": "es", "en": "en-us"}}.get(lang, lang)}}}},
        "headings": {{
            "fontFamily": BODY_FONT, "color": ACCENT,
            "levels": [
                # Always spell out H1 breakBefore: once `headings` exists, the default recto break is gone.
                {{"level": 1, "fontSize": pt(22), "breakBefore": {{"enabled": True, "parity": "odd"}}, "span": "page"}},
                {{"level": 2, "fontSize": pt(12)}},
            ],
        }},
        "header": {{"elements": [
            text_el("folio-odd", "{{pageNumber}}", place("page", "top-right", x=-MARGIN_OUTER, y=10, width=20, height=5),
                    font=BODY_FONT, size=8, fill=INK, align="right", parity="odd", pages="body"),
            text_el("folio-even", "{{pageNumber}}", place("page", "top-left", x=MARGIN_OUTER, y=10, width=20, height=5),
                    font=BODY_FONT, size=8, fill=INK, align="left", parity="even", pages="body"),
        ]}},
        "footer": {{"elements": []}},
        "calloutStyles": [{{"id": "note", "name": "Note"}}],
        "paragraphStyles": [],
        "resourceTypes": resource_types(lang),
    }}


def resource_types(lang: str) -> list:
    es = lang.startswith("es")
    return [
        {{"id": "figure", "name": "Figura" if es else "Figure", "namePlural": "Figuras" if es else "Figures",
          "shortLabel": "Fig.", "captionPrefix": "Figura" if es else "Figure",
          "numberingTemplate": "{{h1}}.{{n}}", "resetOn": "h1", "counterFormat": "decimal",
          "defaultPlacement": {{"position": "auto", "span": "column"}}}},
        {{"id": "table", "name": "Tabla" if es else "Table", "namePlural": "Tablas" if es else "Tables",
          "shortLabel": "Tabla" if es else "Table", "captionPrefix": "Tabla" if es else "Table",
          "numberingTemplate": "{{h1}}.{{n}}", "resetOn": "h1", "counterFormat": "decimal",
          "defaultPlacement": {{"position": "auto", "span": "column"}}}},
    ]


def resources() -> list:
    path = HERE / "resources.json"
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else []


def main() -> None:
    primary = LANGS[0]
    manifest = {{
        "version": 2, "id": ID, "name": NAME, "locale": primary, "locales": LANGS,
        "view": {{"canvasScope": "book"}},
        "chapters": {{lang: chapters_from_dir(HERE, lang) for lang in LANGS}},
        "config": config(primary),
        "localized": {{lang: {{"config": {{k: v for k, v in config(lang).items()
                                        if k in ("locale", "bodyText", "resourceTypes")}}}}
                      for lang in LANGS[1:]}},
        "resources": [{{k: v for k, v in r.items() if k != "source"}} for r in resources()],
        "fonts": font_families(HERE),
    }}
    print("wrote", write_manifest(HERE, manifest))


if __name__ == "__main__":
    main()
'''


def cmd_init(args) -> None:
    project = Path(args.project)
    langs = args.lang or ["en"]
    for d in ["resources", "fonts", "source"] + [f"chapters/{l}" for l in langs]:
        (project / d).mkdir(parents=True, exist_ok=True)
    build = project / "build_preset.py"
    if build.exists() and not args.force:
        sys.exit(f"{build} exists (use --force)")
    kit_dir = str(Path(__file__).resolve().parent)
    build.write_text(TEMPLATE.format(id=args.id, name=args.name, langs=langs, kit_dir=kit_dir), encoding="utf-8")
    os.chmod(build, 0o755)
    print(f"created {project}/ (chapters/{', chapters/'.join(langs)}, resources/, fonts/, source/, build_preset.py)")


def cmd_pack(args) -> None:
    project = Path(args.project).resolve()
    manifest = json.loads((project / "preset.json").read_text(encoding="utf-8"))
    out = Path(args.out or f"{manifest['id']}.postext").resolve()
    skip_fonts = {v["file"] for f in manifest.get("fonts", []) if f.get("redistributable") is False for v in f["variants"]}
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        for p in sorted(project.rglob("*")):
            rel = p.relative_to(project).as_posix()
            if not p.is_file() or any(part.startswith(".") for part in rel.split("/")):
                continue
            if rel.startswith(("source/", "__pycache__/")) or rel in skip_fonts or rel in ("layouts.json",):
                continue
            if p.suffix in (".py",) or rel in ("resources.json", "chapters.json", "report.md", "roles.json"):
                continue
            z.write(p, rel)
    if skip_fonts:
        print(f"left out {len(skip_fonts)} non-redistributable font file(s)")
    print(f"wrote {out}")


def cmd_index(args) -> None:
    root = Path(args.root).resolve()
    presets = []
    for mf in sorted(root.rglob("preset.json")):
        if any(part.startswith(".") for part in mf.relative_to(root).parts):
            continue
        m = json.loads(mf.read_text(encoding="utf-8"))
        entry = {"id": m["id"], "dir": mf.parent.relative_to(root).as_posix(), "name": m["name"]}
        for k in ("description", "locale", "locales", "thumbnail", "license", "credits", "tags"):
            if m.get(k):
                entry[k] = m[k]
        presets.append(entry)
    (root / "index.json").write_text(json.dumps({"version": 1, "presets": presets}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {root / 'index.json'} ({len(presets)} presets)")


def cmd_fonts(args) -> None:
    print(json.dumps(font_families(args.project), ensure_ascii=False, indent=2))


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("init")
    p.add_argument("project")
    p.add_argument("--id", required=True)
    p.add_argument("--name", required=True)
    p.add_argument("--lang", action="append", help="content locale; repeat for a bilingual book (first = primary)")
    p.add_argument("--force", action="store_true")
    p = sub.add_parser("pack")
    p.add_argument("project")
    p.add_argument("--out")
    p = sub.add_parser("index")
    p.add_argument("root")
    p = sub.add_parser("fonts")
    p.add_argument("project")
    args = ap.parse_args()
    {"init": cmd_init, "pack": cmd_pack, "index": cmd_index, "fonts": cmd_fonts}[args.cmd](args)


if __name__ == "__main__":
    main()
