/**
 * The abbreviations the site's prose uses, with their expansion in each
 * locale (WCAG 3.1.4). The docs and Cookbook pipelines wrap the first
 * occurrence on a page in `<abbr title="…">` (rehypeAbbr.ts); the glossary
 * lists them all, which covers pages whose text comes from the messages.
 *
 * Isomorphic: no Node or React imports.
 */
import type { SiteLocale } from "@/i18n/locales";

export interface Abbreviation {
  /** Stable anchor on the glossary page: `abbr-<id>`. */
  id: string;
  /** The written form, matched case-sensitively as a whole word. */
  abbr: string;
  /** Other spellings of the same abbreviation in one locale (RGPD for GDPR). */
  forms?: Partial<Record<SiteLocale, string[]>>;
  /** Also matched with a plural "s" (PDFs, APIs). */
  plural?: boolean;
  expansion: Record<SiteLocale, string>;
}

export const ABBREVIATIONS: readonly Abbreviation[] = [
  { id: "api", abbr: "API", plural: true, expansion: { en: "application programming interface", es: "interfaz de programación de aplicaciones", zh: "应用程序编程接口", ca: "interfície de programació d'aplicacions", ar: "واجهة برمجة التطبيقات (application programming interface)", ja: "アプリケーション・プログラミング・インターフェース", pt: "interface de programação de aplicações" } },
  { id: "apa", abbr: "APA", expansion: { en: "American Psychological Association (a citation style)", es: "American Psychological Association (un estilo de citas)", zh: "美国心理学会（一种引文格式）", ca: "American Psychological Association (un estil de citació)", ar: "الجمعية الأمريكية لعلم النفس (American Psychological Association)، وهو أيضًا اسم أسلوب استشهاد", ja: "アメリカ心理学会（American Psychological Association）、引用スタイルの一つ", pt: "American Psychological Association (um estilo de citação)" } },
  { id: "ascii", abbr: "ASCII", expansion: { en: "American Standard Code for Information Interchange", es: "American Standard Code for Information Interchange, código estándar estadounidense para el intercambio de información", zh: "美国信息交换标准代码", ca: "American Standard Code for Information Interchange, codi estàndard estatunidenc per a l'intercanvi d'informació", ar: "الشيفرة الأمريكية القياسية لتبادل المعلومات (American Standard Code for Information Interchange)", ja: "American Standard Code for Information Interchange（情報交換用米国標準コード）", pt: "American Standard Code for Information Interchange, código padrão americano para o intercâmbio de informações" } },
  { id: "ast", abbr: "AST", plural: true, expansion: { en: "abstract syntax tree", es: "árbol de sintaxis abstracta", zh: "抽象语法树", ca: "arbre de sintaxi abstracta", ar: "شجرة النحو المجردة (abstract syntax tree)", ja: "抽象構文木（abstract syntax tree）", pt: "árvore de sintaxe abstrata" } },
  { id: "bcp", abbr: "BCP", expansion: { en: "Best Current Practice (BCP 47 defines language tags)", es: "Best Current Practice (la BCP 47 define las etiquetas de idioma)", zh: "最佳现行实践（BCP 47 规定语言标签）", ca: "Best Current Practice (la BCP 47 defineix les etiquetes de llengua)", ar: "أفضل الممارسات الحالية (Best Current Practice)، وتعرّف BCP 47 وسوم اللغات", ja: "Best Current Practice（BCP 47が言語タグを定義）", pt: "Best Current Practice (a BCP 47 define as etiquetas de idioma)" } },
  { id: "cdn", abbr: "CDN", plural: true, expansion: { en: "content delivery network", es: "red de distribución de contenidos", zh: "内容分发网络", ca: "xarxa de distribució de continguts", ar: "شبكة توصيل المحتوى (content delivery network)", ja: "コンテンツ配信ネットワーク（content delivery network）", pt: "rede de distribuição de conteúdo" } },
  { id: "cff", abbr: "CFF", expansion: { en: "Compact Font Format", es: "Compact Font Format, formato compacto de fuentes", zh: "紧凑字体格式", ca: "Compact Font Format, format compacte de fonts", ar: "صيغة الخط المضغوطة (Compact Font Format)", ja: "Compact Font Format（コンパクト・フォント・フォーマット）", pt: "Compact Font Format, formato compacto de fontes" } },
  { id: "cjk", abbr: "CJK", expansion: { en: "Chinese, Japanese and Korean", es: "chino, japonés y coreano", zh: "中文、日文和韩文", ca: "xinès, japonès i coreà", ar: "الصينية واليابانية والكورية", ja: "中国語・日本語・韓国語", pt: "chinês, japonês e coreano" } },
  { id: "cldr", abbr: "CLDR", expansion: { en: "Unicode Common Locale Data Repository", es: "Common Locale Data Repository de Unicode, el repositorio de datos regionales", zh: "Unicode 通用区域数据库", ca: "Common Locale Data Repository d'Unicode, el repositori de dades regionals", ar: "مستودع بيانات اللغات والمناطق المشترك في Unicode (Unicode Common Locale Data Repository)", ja: "UnicodeのCommon Locale Data Repository（共通ロケールデータリポジトリ）", pt: "Common Locale Data Repository do Unicode, o repositório de dados regionais" } },
  { id: "cli", abbr: "CLI", expansion: { en: "command-line interface", es: "interfaz de línea de órdenes", zh: "命令行界面", ca: "interfície de línia d'ordres", ar: "واجهة سطر الأوامر (command-line interface)", ja: "コマンドライン・インターフェース", pt: "interface de linha de comando" } },
  { id: "clreq", abbr: "clreq", expansion: { en: "Requirements for Chinese Text Layout (W3C)", es: "Requirements for Chinese Text Layout, requisitos de composición del texto chino (W3C)", zh: "中文排版需求（W3C）", ca: "Requirements for Chinese Text Layout, requisits de composició del text xinès (W3C)", ar: "متطلبات تخطيط النص الصيني (Requirements for Chinese Text Layout)، من W3C", ja: "中国語組版の要件（Requirements for Chinese Text Layout、W3C）", pt: "Requirements for Chinese Text Layout, requisitos de composição do texto chinês (W3C)" } },
  { id: "cm", abbr: "cm", expansion: { en: "centimetres", es: "centímetros", zh: "厘米", ca: "centímetres", ar: "سنتيمترات", ja: "センチメートル", pt: "centímetros" } },
  { id: "cmyk", abbr: "CMYK", expansion: { en: "cyan, magenta, yellow and black (key), the four process inks", es: "cian, magenta, amarillo y negro, las cuatro tintas de cuatricromía", zh: "青、品红、黄、黑，印刷四色", ca: "cian, magenta, groc i negre, les quatre tintes de la quadricromia", ar: "السماوي والأرجواني والأصفر والأسود، أحبار الطباعة الأربعة", ja: "シアン、マゼンタ、イエロー、ブラック（キー）、プロセスインキの4色", pt: "ciano, magenta, amarelo e preto, as quatro tintas da quadricromia" } },
  { id: "cors", abbr: "CORS", expansion: { en: "cross-origin resource sharing", es: "intercambio de recursos entre orígenes", zh: "跨源资源共享", ca: "intercanvi de recursos entre orígens", ar: "مشاركة الموارد بين المصادر المختلفة (cross-origin resource sharing)", ja: "オリジン間リソース共有（cross-origin resource sharing）", pt: "compartilhamento de recursos entre origens" } },
  { id: "css", abbr: "CSS", expansion: { en: "Cascading Style Sheets", es: "Cascading Style Sheets, hojas de estilo en cascada", zh: "层叠样式表", ca: "Cascading Style Sheets, fulls d'estil en cascada", ar: "أوراق الأنماط المتتالية (Cascading Style Sheets)", ja: "Cascading Style Sheets（カスケーディング・スタイル・シート）", pt: "Cascading Style Sheets, folhas de estilo em cascata" } },
  { id: "csv", abbr: "CSV", expansion: { en: "comma-separated values", es: "valores separados por comas", zh: "逗号分隔值", ca: "valors separats per comes", ar: "قيم مفصولة بفواصل (comma-separated values)", ja: "カンマ区切り値（comma-separated values）", pt: "valores separados por vírgulas" } },
  { id: "din", abbr: "DIN", expansion: { en: "Deutsches Institut für Normung, the German standards body", es: "Deutsches Institut für Normung, el organismo alemán de normalización", zh: "德国标准化学会", ca: "Deutsches Institut für Normung, l'organisme alemany de normalització", ar: "المعهد الألماني للتوحيد القياسي (Deutsches Institut für Normung)", ja: "ドイツ規格協会（Deutsches Institut für Normung）", pt: "Deutsches Institut für Normung, o órgão alemão de normalização" } },
  { id: "docx", abbr: "DOCX", expansion: { en: "Word document (Office Open XML)", es: "documento de Word (Office Open XML)", zh: "Word 文档（Office Open XML）", ca: "document de Word (Office Open XML)", ar: "مستند Word بصيغة Office Open XML", ja: "Word文書（Office Open XML）", pt: "documento do Word (Office Open XML)" } },
  { id: "dom", abbr: "DOM", expansion: { en: "Document Object Model, the browser's tree of a page", es: "Document Object Model, el árbol con que el navegador representa la página", zh: "文档对象模型，浏览器中页面的节点树", ca: "Document Object Model, l'arbre amb què el navegador representa la pàgina", ar: "نموذج كائن المستند (Document Object Model)، أي شجرة الصفحة في المتصفح", ja: "Document Object Model（ドキュメント・オブジェクト・モデル）、ブラウザーがページを表すツリー", pt: "Document Object Model, a árvore com que o navegador representa a página" } },
  { id: "dpi", abbr: "DPI", expansion: { en: "dots per inch", es: "puntos por pulgada", zh: "每英寸点数", ca: "punts per polzada", ar: "نقطة في البوصة (dots per inch)", ja: "1インチあたりのドット数（dots per inch）", pt: "pontos por polegada" } },
  { id: "eea", abbr: "EEA", expansion: { en: "European Environment Agency", es: "Agencia Europea de Medio Ambiente", zh: "欧洲环境署", ca: "Agència Europea de Medi Ambient", ar: "الوكالة الأوروبية للبيئة (European Environment Agency)", ja: "欧州環境機関（European Environment Agency）", pt: "Agência Europeia do Ambiente" } },
  { id: "eg", abbr: "e.g.", expansion: { en: "for example", es: "por ejemplo", zh: "例如", ca: "per exemple", ar: "مثلًا", ja: "たとえば", pt: "por exemplo" } },
  { id: "epub", abbr: "EPUB", expansion: { en: "electronic publication, the standard e-book format", es: "publicación electrónica, el formato estándar de libro electrónico", zh: "电子出版物，标准电子书格式", ca: "publicació electrònica, el format estàndard de llibre electrònic", ar: "النشر الإلكتروني (electronic publication)، الصيغة القياسية للكتب الإلكترونية", ja: "電子出版物（electronic publication）、電子書籍の標準フォーマット", pt: "publicação eletrônica, o formato padrão de livro digital" } },
  { id: "esm", abbr: "ESM", expansion: { en: "ECMAScript modules", es: "módulos ECMAScript", zh: "ECMAScript 模块", ca: "mòduls ECMAScript", ar: "وحدات ECMAScript", ja: "ECMAScriptモジュール", pt: "módulos ECMAScript" } },
  { id: "gb-t", abbr: "GB/T", expansion: { en: "recommended national standard of China (Guobiao tuijian)", es: "norma nacional recomendada de China (Guobiao tuijian)", zh: "推荐性国家标准", ca: "norma nacional recomanada de la Xina (Guobiao tuijian)", ar: "معيار وطني صيني موصى به (Guobiao tuijian)", ja: "中国の推奨国家規格（推荐性国家标准、Guobiao tuijian）", pt: "norma nacional recomendada da China (Guobiao tuijian)" } },
  { id: "gdp", abbr: "GDP", expansion: { en: "gross domestic product", es: "producto interior bruto", zh: "国内生产总值", ca: "producte interior brut", ar: "الناتج المحلي الإجمالي", ja: "国内総生産", pt: "produto interno bruto" } },
  { id: "gdpr", abbr: "GDPR", forms: { es: ["RGPD"], ca: ["RGPD"] }, expansion: { en: "General Data Protection Regulation (EU)", es: "Reglamento General de Protección de Datos (UE)", zh: "《通用数据保护条例》（欧盟）", ca: "Reglament General de Protecció de Dades (UE)", ar: "اللائحة العامة لحماية البيانات في الاتحاد الأوروبي (General Data Protection Regulation)", ja: "EU一般データ保護規則（General Data Protection Regulation）", pt: "Regulamento Geral sobre a Proteção de Dados (UE)" } },
  { id: "gfm", abbr: "GFM", expansion: { en: "GitHub Flavored Markdown", es: "GitHub Flavored Markdown, la variante de Markdown de GitHub", zh: "GitHub 风格的 Markdown", ca: "GitHub Flavored Markdown, la variant de Markdown de GitHub", ar: "صيغة Markdown في GitHub (GitHub Flavored Markdown)", ja: "GitHub Flavored Markdown（GitHub版のMarkdown）", pt: "GitHub Flavored Markdown, a variante de Markdown do GitHub" } },
  { id: "gif", abbr: "GIF", plural: true, expansion: { en: "Graphics Interchange Format", es: "Graphics Interchange Format, formato de intercambio de gráficos", zh: "图形交换格式", ca: "Graphics Interchange Format, format d'intercanvi de gràfics", ar: "صيغة تبادل الرسوميات (Graphics Interchange Format)", ja: "Graphics Interchange Format（グラフィックス・インターチェンジ・フォーマット）", pt: "Graphics Interchange Format, formato de intercâmbio de gráficos" } },
  { id: "gpu", abbr: "GPU", expansion: { en: "graphics processing unit", es: "unidad de procesamiento gráfico", zh: "图形处理器", ca: "unitat de processament gràfic", ar: "وحدة معالجة الرسوميات (graphics processing unit)", ja: "グラフィックス処理装置（graphics processing unit）", pt: "unidade de processamento gráfico" } },
  { id: "html", abbr: "HTML", expansion: { en: "HyperText Markup Language", es: "HyperText Markup Language, lenguaje de marcado de hipertexto", zh: "超文本标记语言", ca: "HyperText Markup Language, llenguatge de marcatge d'hipertext", ar: "لغة ترميز النص الفائق (HyperText Markup Language)", ja: "HyperText Markup Language（ハイパーテキスト・マークアップ言語）", pt: "HyperText Markup Language, linguagem de marcação de hipertexto" } },
  { id: "http", abbr: "HTTP", expansion: { en: "Hypertext Transfer Protocol", es: "Hypertext Transfer Protocol, protocolo de transferencia de hipertexto", zh: "超文本传输协议", ca: "Hypertext Transfer Protocol, protocol de transferència d'hipertext", ar: "بروتوكول نقل النص الفائق (Hypertext Transfer Protocol)", ja: "Hypertext Transfer Protocol（ハイパーテキスト転送プロトコル）", pt: "Hypertext Transfer Protocol, protocolo de transferência de hipertexto" } },
  { id: "icc", abbr: "ICC", expansion: { en: "International Color Consortium (colour profiles)", es: "International Color Consortium (perfiles de color)", zh: "国际色彩联盟（色彩配置文件）", ca: "International Color Consortium (perfils de color)", ar: "الاتحاد الدولي للألوان (International Color Consortium)، صاحب ملفات تعريف الألوان", ja: "International Color Consortium（国際カラーコンソーシアム、カラープロファイルの規格団体）", pt: "International Color Consortium (perfis de cor)" } },
  { id: "idml", abbr: "IDML", expansion: { en: "InDesign Markup Language", es: "InDesign Markup Language, el formato de intercambio de InDesign", zh: "InDesign 标记语言", ca: "InDesign Markup Language, el format d'intercanvi d'InDesign", ar: "لغة ترميز InDesign (InDesign Markup Language)", ja: "InDesign Markup Language（InDesignの交換用フォーマット）", pt: "InDesign Markup Language, o formato de intercâmbio do InDesign" } },
  { id: "ie", abbr: "i.e.", expansion: { en: "that is", es: "es decir", zh: "即", ca: "és a dir", ar: "أي", ja: "つまり", pt: "isto é" } },
  { id: "isbn", abbr: "ISBN", expansion: { en: "International Standard Book Number", es: "International Standard Book Number, número internacional normalizado del libro", zh: "国际标准书号", ca: "International Standard Book Number, número internacional normalitzat del llibre", ar: "الرقم الدولي المعياري للكتاب (International Standard Book Number)", ja: "国際標準図書番号（International Standard Book Number）", pt: "International Standard Book Number, número padrão internacional de livro" } },
  { id: "jats", abbr: "JATS", expansion: { en: "Journal Article Tag Suite", es: "Journal Article Tag Suite, el formato XML de artículos científicos", zh: "期刊文章标签集", ca: "Journal Article Tag Suite, el format XML d'articles científics", ar: "مجموعة وسوم مقالات الدوريات (Journal Article Tag Suite)، صيغة XML للمقالات العلمية", ja: "Journal Article Tag Suite（学術論文用のXMLフォーマット）", pt: "Journal Article Tag Suite, o formato XML de artigos científicos" } },
  { id: "jis", abbr: "JIS", expansion: { en: "Japanese Industrial Standards", es: "Japanese Industrial Standards, normas industriales japonesas", zh: "日本工业标准", ca: "Japanese Industrial Standards, normes industrials japoneses", ar: "المعايير الصناعية اليابانية (Japanese Industrial Standards)", ja: "日本産業規格（Japanese Industrial Standards）", pt: "Japanese Industrial Standards, normas industriais japonesas" } },
  { id: "jlreq", abbr: "JLREQ", expansion: { en: "Requirements for Japanese Text Layout (W3C)", es: "Requirements for Japanese Text Layout, requisitos de composición del texto japonés (W3C)", zh: "日文排版需求（W3C）", ca: "Requirements for Japanese Text Layout, requisits de composició del text japonès (W3C)", ar: "متطلبات تخطيط النص الياباني (Requirements for Japanese Text Layout)، من W3C", ja: "日本語組版処理の要件（Requirements for Japanese Text Layout、W3C）", pt: "Requirements for Japanese Text Layout, requisitos de composição do texto japonês (W3C)" } },
  { id: "jpeg", abbr: "JPEG", expansion: { en: "Joint Photographic Experts Group, the photo image format", es: "Joint Photographic Experts Group, el formato de imagen fotográfica", zh: "联合图像专家组，常用的照片图像格式", ca: "Joint Photographic Experts Group, el format d'imatge fotogràfica", ar: "مجموعة خبراء التصوير المشتركة (Joint Photographic Experts Group)، صيغة الصور الفوتوغرافية", ja: "Joint Photographic Experts Group、写真画像のフォーマット", pt: "Joint Photographic Experts Group, o formato de imagem fotográfica" } },
  { id: "json", abbr: "JSON", expansion: { en: "JavaScript Object Notation", es: "JavaScript Object Notation, notación de objetos de JavaScript", zh: "JavaScript 对象表示法", ca: "JavaScript Object Notation, notació d'objectes de JavaScript", ar: "ترميز كائنات JavaScript (JavaScript Object Notation)", ja: "JavaScript Object Notation（JavaScriptのオブジェクト表記法）", pt: "JavaScript Object Notation, notação de objetos do JavaScript" } },
  { id: "jsx", abbr: "JSX", expansion: { en: "JavaScript XML, the tag syntax of React", es: "JavaScript XML, la sintaxis de etiquetas de React", zh: "JavaScript XML，React 的标签语法", ca: "JavaScript XML, la sintaxi d'etiquetes de React", ar: "JavaScript XML، صيغة الوسوم في React", ja: "JavaScript XML、Reactのタグ構文", pt: "JavaScript XML, a sintaxe de tags do React" } },
  { id: "klreq", abbr: "KLREQ", expansion: { en: "Requirements for Hangul Text Layout (W3C)", es: "Requirements for Hangul Text Layout, requisitos de composición del texto coreano (W3C)", zh: "韩文排版需求（W3C）", ca: "Requirements for Hangul Text Layout, requisits de composició del text coreà (W3C)", ar: "متطلبات تخطيط نص الهانغول (Requirements for Hangul Text Layout)، من W3C", ja: "ハングル組版の要件（Requirements for Hangul Text Layout、W3C）", pt: "Requirements for Hangul Text Layout, requisitos de composição do texto coreano (W3C)" } },
  { id: "kp", abbr: "KP", expansion: { en: "Knuth–Plass, the line-breaking algorithm", es: "Knuth-Plass, el algoritmo de corte de líneas", zh: "Knuth-Plass 断行算法", ca: "Knuth-Plass, l'algorisme de tall de línies", ar: "Knuth–Plass، خوارزمية تقسيم الأسطر", ja: "Knuth–Plass、改行アルゴリズム", pt: "Knuth-Plass, o algoritmo de quebra de linhas" } },
  { id: "llm", abbr: "LLM", plural: true, expansion: { en: "large language model", es: "modelo de lenguaje de gran tamaño", zh: "大语言模型", ca: "model de llenguatge de grans dimensions", ar: "نموذج لغوي كبير (large language model)", ja: "大規模言語モデル（large language model）", pt: "modelo de linguagem de grande escala" } },
  { id: "mdx", abbr: "MDX", expansion: { en: "Markdown with JSX components", es: "Markdown con componentes JSX", zh: "可嵌入 JSX 组件的 Markdown", ca: "Markdown amb components JSX", ar: "Markdown مع مكوّنات JSX", ja: "JSXコンポーネントを埋め込めるMarkdown", pt: "Markdown com componentes JSX" } },
  { id: "mit", abbr: "MIT", expansion: { en: "Massachusetts Institute of Technology, which wrote the MIT License", es: "Massachusetts Institute of Technology, origen de la licencia MIT", zh: "麻省理工学院，MIT 许可证出自该校", ca: "Massachusetts Institute of Technology, origen de la llicència MIT", ar: "معهد ماساتشوستس للتقنية (Massachusetts Institute of Technology)، الذي كتب رخصة MIT", ja: "マサチューセッツ工科大学（Massachusetts Institute of Technology）、MITライセンスの起草元", pt: "Massachusetts Institute of Technology, origem da licença MIT" } },
  { id: "mm", abbr: "mm", expansion: { en: "millimetres", es: "milímetros", zh: "毫米", ca: "mil·límetres", ar: "مليمترات", ja: "ミリメートル", pt: "milímetros" } },
  { id: "npm", abbr: "npm", expansion: { en: "the Node.js package registry and its command-line client", es: "el registro de paquetes de Node.js y su cliente de línea de órdenes", zh: "Node.js 包注册表及其命令行客户端", ca: "el registre de paquets de Node.js i el seu client de línia d'ordres", ar: "سجل حزم Node.js وأداة سطر الأوامر الخاصة به", ja: "Node.jsのパッケージレジストリーとそのコマンドライン・クライアント", pt: "o registro de pacotes do Node.js e seu cliente de linha de comando" } },
  { id: "ocr", abbr: "OCR", expansion: { en: "optical character recognition", es: "reconocimiento óptico de caracteres", zh: "光学字符识别", ca: "reconeixement òptic de caràcters", ar: "التعرّف الضوئي على الحروف (optical character recognition)", ja: "光学文字認識（optical character recognition）", pt: "reconhecimento óptico de caracteres" } },
  { id: "odt", abbr: "ODT", expansion: { en: "OpenDocument text document", es: "documento de texto OpenDocument", zh: "OpenDocument 文本文档", ca: "document de text OpenDocument", ar: "مستند نصي بصيغة OpenDocument", ja: "OpenDocumentテキスト文書", pt: "documento de texto OpenDocument" } },
  { id: "ofl", abbr: "OFL", expansion: { en: "SIL Open Font License", es: "SIL Open Font License, licencia abierta de fuentes", zh: "SIL 开放字体许可证", ca: "SIL Open Font License, llicència oberta de fonts", ar: "رخصة الخطوط المفتوحة من SIL (SIL Open Font License)", ja: "SIL Open Font License（SILオープン・フォント・ライセンス）", pt: "SIL Open Font License, licença aberta de fontes" } },
  { id: "otf", abbr: "OTF", expansion: { en: "OpenType font file", es: "archivo de fuente OpenType", zh: "OpenType 字体文件", ca: "fitxer de font OpenType", ar: "ملف خط بصيغة OpenType", ja: "OpenTypeフォントファイル", pt: "arquivo de fonte OpenType" } },
  { id: "pdf", abbr: "PDF", plural: true, expansion: { en: "Portable Document Format", es: "Portable Document Format, formato de documento portátil", zh: "便携式文档格式", ca: "Portable Document Format, format de document portàtil", ar: "صيغة المستند المحمولة (Portable Document Format)", ja: "Portable Document Format（ポータブル・ドキュメント・フォーマット）", pt: "Portable Document Format, formato de documento portátil" } },
  { id: "pdf-ua", abbr: "PDF/UA", expansion: { en: "PDF/Universal Accessibility, the ISO 14289 standard for accessible PDF", es: "PDF/Universal Accessibility, la norma ISO 14289 de PDF accesible", zh: "PDF/通用无障碍，无障碍 PDF 的 ISO 14289 标准", ca: "PDF/Universal Accessibility, la norma ISO 14289 de PDF accessible", ar: "PDF/Universal Accessibility، معيار ISO 14289 لملفات PDF الميسّرة", ja: "PDF/Universal Accessibility、アクセシブルなPDFの規格ISO 14289", pt: "PDF/Universal Accessibility, a norma ISO 14289 de PDF acessível" } },
  { id: "pdf-x", abbr: "PDF/X", expansion: { en: "the ISO 15930 family of PDF standards for print exchange", es: "la familia de normas ISO 15930 de PDF para imprenta", zh: "用于印刷交换的 ISO 15930 系列 PDF 标准", ca: "la família de normes ISO 15930 de PDF per a impremta", ar: "عائلة معايير ISO 15930 لملفات PDF المعدّة لتبادل ملفات الطباعة", ja: "印刷用データ交換のためのPDF規格群ISO 15930", pt: "a família de normas ISO 15930 de PDF para impressão gráfica" } },
  { id: "png", abbr: "PNG", plural: true, expansion: { en: "Portable Network Graphics", es: "Portable Network Graphics, formato de imagen sin pérdida", zh: "便携式网络图形", ca: "Portable Network Graphics, format d'imatge sense pèrdua", ar: "رسوميات الشبكة المحمولة (Portable Network Graphics)", ja: "Portable Network Graphics（ポータブル・ネットワーク・グラフィックス）", pt: "Portable Network Graphics, formato de imagem sem perda" } },
  { id: "pptx", abbr: "PPTX", expansion: { en: "PowerPoint presentation (Office Open XML)", es: "presentación de PowerPoint (Office Open XML)", zh: "PowerPoint 演示文稿（Office Open XML）", ca: "presentació de PowerPoint (Office Open XML)", ar: "عرض تقديمي في PowerPoint بصيغة Office Open XML", ja: "PowerPointプレゼンテーション（Office Open XML）", pt: "apresentação do PowerPoint (Office Open XML)" } },
  { id: "pt", abbr: "pt", expansion: { en: "points (1/72 inch)", es: "puntos (1/72 de pulgada)", zh: "点（1/72 英寸）", ca: "punts (1/72 de polzada)", ar: "نقاط (1/72 من البوصة)", ja: "ポイント（1/72インチ）", pt: "pontos (1/72 de polegada)" } },
  { id: "px", abbr: "px", expansion: { en: "CSS pixels", es: "píxeles CSS", zh: "CSS 像素", ca: "píxels CSS", ar: "بكسلات CSS", ja: "CSSピクセル", pt: "pixels CSS" } },
  { id: "rae", abbr: "RAE", expansion: { en: "Real Academia Española", es: "Real Academia Española", zh: "西班牙皇家语言学院", ca: "Real Academia Española", ar: "الأكاديمية الملكية الإسبانية (Real Academia Española)", ja: "スペイン王立アカデミー（Real Academia Española）", pt: "Real Academia Española" } },
  { id: "rgb", abbr: "RGB", expansion: { en: "red, green and blue, the screen colour channels", es: "rojo, verde y azul, los canales de color de la pantalla", zh: "红、绿、蓝，屏幕的颜色通道", ca: "vermell, verd i blau, els canals de color de la pantalla", ar: "الأحمر والأخضر والأزرق، قنوات الألوان في الشاشة", ja: "赤・緑・青、画面の色チャンネル", pt: "vermelho, verde e azul, os canais de cor da tela" } },
  { id: "roc", abbr: "ROC", expansion: { en: "Republic of China (Minguo calendar)", es: "República de China (calendario Minguo)", zh: "中华民国（民国纪年）", ca: "República de la Xina (calendari Minguo)", ar: "جمهورية الصين (تقويم مينغوو)", ja: "中華民国（民国紀元）", pt: "República da China (calendário Minguo)" } },
  { id: "ssr", abbr: "SSR", expansion: { en: "server-side rendering", es: "renderizado en el servidor", zh: "服务器端渲染", ca: "renderització al servidor", ar: "الإخراج على الخادم (server-side rendering)", ja: "サーバーサイドレンダリング（server-side rendering）", pt: "renderização no servidor" } },
  { id: "svg", abbr: "SVG", plural: true, expansion: { en: "Scalable Vector Graphics", es: "Scalable Vector Graphics, gráficos vectoriales escalables", zh: "可缩放矢量图形", ca: "Scalable Vector Graphics, gràfics vectorials escalables", ar: "الرسوميات المتجهة القابلة للتحجيم (Scalable Vector Graphics)", ja: "Scalable Vector Graphics（スケーラブル・ベクター・グラフィックス）", pt: "Scalable Vector Graphics, gráficos vetoriais escaláveis" } },
  { id: "toc", abbr: "TOC", expansion: { en: "table of contents", es: "índice general (tabla de contenidos)", zh: "目录", ca: "índex general (taula de continguts)", ar: "جدول المحتويات (table of contents)", ja: "目次（table of contents）", pt: "sumário (table of contents)" } },
  { id: "tsv", abbr: "TSV", expansion: { en: "tab-separated values", es: "valores separados por tabuladores", zh: "制表符分隔值", ca: "valors separats per tabuladors", ar: "قيم مفصولة بمسافات الجدولة (tab-separated values)", ja: "タブ区切り値（tab-separated values）", pt: "valores separados por tabulações" } },
  { id: "ttf", abbr: "TTF", expansion: { en: "TrueType font file", es: "archivo de fuente TrueType", zh: "TrueType 字体文件", ca: "fitxer de font TrueType", ar: "ملف خط بصيغة TrueType", ja: "TrueTypeフォントファイル", pt: "arquivo de fonte TrueType" } },
  { id: "uax", abbr: "UAX", expansion: { en: "Unicode Standard Annex", es: "Unicode Standard Annex, anexo del estándar Unicode", zh: "Unicode 标准附件", ca: "Unicode Standard Annex, annex de l'estàndard Unicode", ar: "ملحق معيار Unicode (Unicode Standard Annex)", ja: "Unicode標準附属書（Unicode Standard Annex）", pt: "Unicode Standard Annex, anexo do padrão Unicode" } },
  { id: "ui", abbr: "UI", plural: true, expansion: { en: "user interface", es: "interfaz de usuario", zh: "用户界面", ca: "interfície d'usuari", ar: "واجهة المستخدم (user interface)", ja: "ユーザーインターフェース", pt: "interface do usuário" } },
  { id: "uri", abbr: "URI", plural: true, expansion: { en: "Uniform Resource Identifier", es: "Uniform Resource Identifier, identificador uniforme de recursos", zh: "统一资源标识符", ca: "Uniform Resource Identifier, identificador uniforme de recursos", ar: "المعرّف الموحّد للموارد (Uniform Resource Identifier)", ja: "Uniform Resource Identifier（統一資源識別子）", pt: "Uniform Resource Identifier, identificador uniforme de recursos" } },
  { id: "url", abbr: "URL", plural: true, expansion: { en: "Uniform Resource Locator, a web address", es: "Uniform Resource Locator, una dirección web", zh: "统一资源定位符，即网址", ca: "Uniform Resource Locator, una adreça web", ar: "محدّد الموارد الموحّد (Uniform Resource Locator)، أي عنوان الويب", ja: "Uniform Resource Locator、Webのアドレス", pt: "Uniform Resource Locator, um endereço web" } },
  { id: "utc", abbr: "UTC", expansion: { en: "Coordinated Universal Time", es: "tiempo universal coordinado", zh: "协调世界时", ca: "temps universal coordinat", ar: "التوقيت العالمي المنسّق (Coordinated Universal Time)", ja: "協定世界時", pt: "tempo universal coordenado" } },
  { id: "vdt", abbr: "VDT", expansion: { en: "Virtual Document Tree, Postext's laid-out document", es: "Virtual Document Tree, el documento maquetado de Postext", zh: "虚拟文档树，Postext 排好版的文档", ca: "Virtual Document Tree, el document maquetat de Postext", ar: "شجرة المستند الافتراضية (Virtual Document Tree)، أي المستند بعد أن ينضّده Postext", ja: "Virtual Document Tree、Postextのレイアウト済み文書", pt: "Virtual Document Tree, o documento diagramado do Postext" } },
  { id: "w3c", abbr: "W3C", expansion: { en: "World Wide Web Consortium", es: "World Wide Web Consortium, el consorcio que publica los estándares web", zh: "万维网联盟", ca: "World Wide Web Consortium, el consorci que publica els estàndards web", ar: "اتحاد شبكة الويب العالمية (World Wide Web Consortium)", ja: "World Wide Web Consortium（ワールド・ワイド・ウェブ・コンソーシアム）", pt: "World Wide Web Consortium, o consórcio que publica os padrões da web" } },
  { id: "wai", abbr: "WAI", expansion: { en: "Web Accessibility Initiative (W3C)", es: "Web Accessibility Initiative, la iniciativa de accesibilidad web del W3C", zh: "W3C 网页无障碍倡议", ca: "Web Accessibility Initiative, la iniciativa d'accessibilitat web del W3C", ar: "مبادرة إتاحة الويب (Web Accessibility Initiative) في W3C", ja: "Web Accessibility Initiative（W3CのWebアクセシビリティ・イニシアティブ）", pt: "Web Accessibility Initiative, a iniciativa de acessibilidade web do W3C" } },
  { id: "wcag", abbr: "WCAG", expansion: { en: "Web Content Accessibility Guidelines", es: "Web Content Accessibility Guidelines, pautas de accesibilidad para el contenido web", zh: "网页内容无障碍指南", ca: "Web Content Accessibility Guidelines, pautes d'accessibilitat per al contingut web", ar: "إرشادات إتاحة محتوى الويب (Web Content Accessibility Guidelines)", ja: "Web Content Accessibility Guidelines（Webコンテンツ・アクセシビリティ・ガイドライン）", pt: "Web Content Accessibility Guidelines, diretrizes de acessibilidade para conteúdo web" } },
  { id: "woff", abbr: "WOFF", expansion: { en: "Web Open Font Format", es: "Web Open Font Format, formato de fuentes para la web", zh: "Web 开放字体格式", ca: "Web Open Font Format, format de fonts per al web", ar: "صيغة الخطوط المفتوحة للويب (Web Open Font Format)", ja: "Web Open Font Format（Webオープン・フォント・フォーマット）", pt: "Web Open Font Format, formato de fontes para a web" } },
  { id: "woff2", abbr: "WOFF2", expansion: { en: "Web Open Font Format 2, compressed with Brotli", es: "Web Open Font Format 2, comprimido con Brotli", zh: "Web 开放字体格式 2，使用 Brotli 压缩", ca: "Web Open Font Format 2, comprimit amb Brotli", ar: "صيغة الخطوط المفتوحة للويب 2 (Web Open Font Format 2)، مضغوطة بخوارزمية Brotli", ja: "Web Open Font Format 2、Brotliで圧縮した形式", pt: "Web Open Font Format 2, comprimido com Brotli" } },
  { id: "wysiwyg", abbr: "WYSIWYG", expansion: { en: "what you see is what you get", es: "what you see is what you get, lo que ves es lo que obtienes", zh: "所见即所得", ca: "what you see is what you get, el que veus és el que obtens", ar: "ما تراه هو ما تحصل عليه (what you see is what you get)", ja: "what you see is what you get（見たままが得られる）", pt: "what you see is what you get, o que você vê é o que você obtém" } },
  { id: "xmp", abbr: "XMP", expansion: { en: "Extensible Metadata Platform", es: "Extensible Metadata Platform, plataforma de metadatos extensible", zh: "可扩展元数据平台", ca: "Extensible Metadata Platform, plataforma de metadades extensible", ar: "منصة البيانات الوصفية القابلة للتوسيع (Extensible Metadata Platform)", ja: "Extensible Metadata Platform（拡張可能メタデータ・プラットフォーム）", pt: "Extensible Metadata Platform, plataforma extensível de metadados" } },
  { id: "yaml", abbr: "YAML", expansion: { en: "YAML Ain't Markup Language, a plain-text data format", es: "YAML Ain't Markup Language, un formato de datos en texto plano", zh: "YAML 不是标记语言，一种纯文本数据格式", ca: "YAML Ain't Markup Language, un format de dades en text pla", ar: "YAML Ain't Markup Language، صيغة بيانات بنص عادي", ja: "YAML Ain't Markup Language、プレーンテキストのデータ形式", pt: "YAML Ain't Markup Language, um formato de dados em texto simples" } },
  { id: "zip", abbr: "ZIP", expansion: { en: "a compressed archive format", es: "un formato de archivo comprimido", zh: "一种压缩归档格式", ca: "un format de fitxer comprimit", ar: "صيغة أرشيف مضغوط", ja: "圧縮アーカイブのフォーマット", pt: "um formato de arquivo compactado" } },
];

export interface AbbreviationEntry {
  id: string;
  /** The form written on the page in this locale. */
  abbr: string;
  title: string;
}

/** The written forms of one locale, each mapped to its entry. */
export function abbreviationsFor(locale: string): Map<string, AbbreviationEntry> {
  const loc = (locale in ABBREVIATIONS[0]!.expansion ? locale : "en") as SiteLocale;
  const map = new Map<string, AbbreviationEntry>();
  for (const a of ABBREVIATIONS) {
    const title = a.expansion[loc];
    for (const form of [a.abbr, ...(a.forms?.[loc] ?? [])]) {
      map.set(form, { id: a.id, abbr: form, title });
      if (a.plural) map.set(`${form}s`, { id: a.id, abbr: form, title });
    }
  }
  return map;
}

const escape = (s: string) => s.replace(/[.*+?^${}()|[\]\\/]/g, "\\$&");

/** One regular expression for every written form of a locale, longest first
 *  (PDF/UA before PDF), as whole words: not inside a longer word, a number,
 *  a file name or a hyphenated identifier. */
export function abbreviationPattern(locale: string): RegExp {
  const forms = [...abbreviationsFor(locale).keys()].sort((a, b) => b.length - a.length);
  // A `.` before a form makes it a file extension (`file.pdf`); after a
  // form it ends the sentence and is allowed.
  // Latin letters only: Chinese text runs straight into an abbreviation
  // (生成PDF文件) and still counts as a word boundary.
  return new RegExp(`(?<![A-Za-z0-9\\u00C0-\\u024F_\\-./@#])(?:${forms.map(escape).join("|")})(?![A-Za-z0-9\\u00C0-\\u024F_\\-/@])`, "g");
}
