"use client";

import Link from "next/link";
import { PostextSandbox, DEFAULT_MARKDOWN_EN, DEFAULT_MARKDOWN_ES } from "postext-sandbox";
import { useTranslations, useLocale } from "next-intl";
import { ThemeToggle } from "@/components/ThemeToggle";
import { CompactLanguageSwitcher } from "@/components/sandbox/CompactLanguageSwitcher";
import type { SandboxLabels } from "postext-sandbox";

export function SandboxPage() {
  const t = useTranslations("Sandbox");
  const locale = useLocale();
  const initialMarkdown = locale === "es" ? DEFAULT_MARKDOWN_ES : DEFAULT_MARKDOWN_EN;

  const labels: SandboxLabels = {
    configuration: t("configuration"),
    resources: t("resources"),
    markdownEditor: t("markdownEditor"),
    canvas: t("canvas"),
    html: t("html"),
    pdf: t("pdf"),
    comingSoon: t("comingSoon"),
    resourcesComingSoonDescription: t("resourcesComingSoonDescription"),
    pdfComingSoonDescription: t("pdfComingSoonDescription"),
    page: t("page"),
    pageBackgroundColor: t("pageBackgroundColor"),
    pageBackgroundColorTooltip: t("pageBackgroundColorTooltip"),
    pageSize: t("pageSize"),
    pageSizeTooltip: t("pageSizeTooltip"),
    custom: t("custom"),
    width: t("width"),
    widthTooltip: t("widthTooltip"),
    height: t("height"),
    heightTooltip: t("heightTooltip"),
    marginTop: t("marginTop"),
    marginBottom: t("marginBottom"),
    marginLeft: t("marginLeft"),
    marginRight: t("marginRight"),
    marginsTooltip: t("marginsTooltip"),
    dpi: t("dpi"),
    dpiTooltip: t("dpiTooltip"),
    cutLines: t("cutLines"),
    cutLinesTooltip: t("cutLinesTooltip"),
    cutLinesBleed: t("cutLinesBleed"),
    cutLinesBleedTooltip: t("cutLinesBleedTooltip"),
    cutLinesMarkLength: t("cutLinesMarkLength"),
    cutLinesMarkLengthTooltip: t("cutLinesMarkLengthTooltip"),
    cutLinesMarkOffset: t("cutLinesMarkOffset"),
    cutLinesMarkOffsetTooltip: t("cutLinesMarkOffsetTooltip"),
    cutLinesMarkWidth: t("cutLinesMarkWidth"),
    cutLinesMarkWidthTooltip: t("cutLinesMarkWidthTooltip"),
    cutLinesColor: t("cutLinesColor"),
    cutLinesColorTooltip: t("cutLinesColorTooltip"),
    baselineGrid: t("baselineGrid"),
    baselineGridTooltip: t("baselineGridTooltip"),
    baselineGridColor: t("baselineGridColor"),
    baselineGridColorTooltip: t("baselineGridColorTooltip"),
    baselineGridLineWidth: t("baselineGridLineWidth"),
    baselineGridLineWidthTooltip: t("baselineGridLineWidthTooltip"),
    debug: t("debug"),
    debugCursorSync: t("debugCursorSync"),
    debugCursorSyncTooltip: t("debugCursorSyncTooltip"),
    debugCursorSyncColor: t("debugCursorSyncColor"),
    debugCursorSyncColorTooltip: t("debugCursorSyncColorTooltip"),
    debugSelectionSync: t("debugSelectionSync"),
    debugSelectionSyncTooltip: t("debugSelectionSyncTooltip"),
    debugSelectionSyncColor: t("debugSelectionSyncColor"),
    debugSelectionSyncColorTooltip: t("debugSelectionSyncColorTooltip"),
    debugLooseLines: t("debugLooseLines"),
    debugLooseLinesTooltip: t("debugLooseLinesTooltip"),
    debugLooseLinesColor: t("debugLooseLinesColor"),
    debugLooseLinesColorTooltip: t("debugLooseLinesColorTooltip"),
    debugLooseLinesThreshold: t("debugLooseLinesThreshold"),
    debugLooseLinesThresholdTooltip: t("debugLooseLinesThresholdTooltip"),
    bodyText: t("bodyText"),
    bodyFont: t("bodyFont"),
    bodyFontTooltip: t("bodyFontTooltip"),
    bodyFontSearch: t("bodyFontSearch"),
    bodyFontNoResults: t("bodyFontNoResults"),
    bodyFontSize: t("bodyFontSize"),
    bodyFontSizeTooltip: t("bodyFontSizeTooltip"),
    bodyLineHeight: t("bodyLineHeight"),
    bodyLineHeightTooltip: t("bodyLineHeightTooltip"),
    bodyParagraphSpacing: t("bodyParagraphSpacing"),
    bodyParagraphSpacingTooltip: t("bodyParagraphSpacingTooltip"),
    bodyColor: t("bodyColor"),
    bodyColorTooltip: t("bodyColorTooltip"),
    bodyBoldColor: t("bodyBoldColor"),
    bodyBoldColorTooltip: t("bodyBoldColorTooltip"),
    bodyItalicColor: t("bodyItalicColor"),
    bodyItalicColorTooltip: t("bodyItalicColorTooltip"),
    bodyTextAlign: t("bodyTextAlign"),
    bodyTextAlignTooltip: t("bodyTextAlignTooltip"),
    bodyTextAlignLeft: t("bodyTextAlignLeft"),
    bodyTextAlignJustify: t("bodyTextAlignJustify"),
    bodyHyphenation: t("bodyHyphenation"),
    bodyHyphenationTooltip: t("bodyHyphenationTooltip"),
    bodyFontWeight: t("bodyFontWeight"),
    bodyFontWeightTooltip: t("bodyFontWeightTooltip"),
    bodyBoldFontWeight: t("bodyBoldFontWeight"),
    bodyBoldFontWeightTooltip: t("bodyBoldFontWeightTooltip"),
    bodyHyphenationLocale: t("bodyHyphenationLocale"),
    bodyHyphenationLocaleTooltip: t("bodyHyphenationLocaleTooltip"),
    bodyFirstLineIndent: t("bodyFirstLineIndent"),
    bodyFirstLineIndentTooltip: t("bodyFirstLineIndentTooltip"),
    bodyHangingIndent: t("bodyHangingIndent"),
    bodyHangingIndentTooltip: t("bodyHangingIndentTooltip"),
    bodyMaxWordSpacing: t("bodyMaxWordSpacing"),
    bodyMaxWordSpacingTooltip: t("bodyMaxWordSpacingTooltip"),
    bodyMinWordSpacing: t("bodyMinWordSpacing"),
    bodyMinWordSpacingTooltip: t("bodyMinWordSpacingTooltip"),
    headings: t("headings"),
    headingsFont: t("headingsFont"),
    headingsFontTooltip: t("headingsFontTooltip"),
    headingsFontSearch: t("headingsFontSearch"),
    headingsFontNoResults: t("headingsFontNoResults"),
    headingsLineHeight: t("headingsLineHeight"),
    headingsLineHeightTooltip: t("headingsLineHeightTooltip"),
    headingsColor: t("headingsColor"),
    headingsColorTooltip: t("headingsColorTooltip"),
    headingsFontWeight: t("headingsFontWeight"),
    headingsFontWeightTooltip: t("headingsFontWeightTooltip"),
    headingsMarginTop: t("headingsMarginTop"),
    headingsMarginTopTooltip: t("headingsMarginTopTooltip"),
    headingsMarginBottom: t("headingsMarginBottom"),
    headingsMarginBottomTooltip: t("headingsMarginBottomTooltip"),
    headingLevel: t("headingLevel"),
    headingFontSize: t("headingFontSize"),
    headingFontSizeTooltip: t("headingFontSizeTooltip"),
    headingLineHeight: t("headingLineHeight"),
    headingLineHeightTooltip: t("headingLineHeightTooltip"),
    headingFont: t("headingFont"),
    headingFontTooltip: t("headingFontTooltip"),
    headingFontSearch: t("headingFontSearch"),
    headingFontNoResults: t("headingFontNoResults"),
    headingColor: t("headingColor"),
    headingColorTooltip: t("headingColorTooltip"),
    headingFontWeight: t("headingFontWeight"),
    headingFontWeightTooltip: t("headingFontWeightTooltip"),
    headingMarginTop: t("headingMarginTop"),
    headingMarginTopTooltip: t("headingMarginTopTooltip"),
    headingMarginBottom: t("headingMarginBottom"),
    headingMarginBottomTooltip: t("headingMarginBottomTooltip"),
    headingNumberingTemplate: t("headingNumberingTemplate"),
    headingNumberingTemplateTooltip: t("headingNumberingTemplateTooltip"),
    headingNumberingTemplatePlaceholder: t("headingNumberingTemplatePlaceholder"),
    headingItalic: t("headingItalic"),
    headingItalicTooltip: t("headingItalicTooltip"),
    unorderedLists: t("unorderedLists"),
    unorderedListsFont: t("unorderedListsFont"),
    unorderedListsFontTooltip: t("unorderedListsFontTooltip"),
    unorderedListsFontSearch: t("unorderedListsFontSearch"),
    unorderedListsFontNoResults: t("unorderedListsFontNoResults"),
    unorderedListsColor: t("unorderedListsColor"),
    unorderedListsColorTooltip: t("unorderedListsColorTooltip"),
    unorderedListsFontWeight: t("unorderedListsFontWeight"),
    unorderedListsFontWeightTooltip: t("unorderedListsFontWeightTooltip"),
    unorderedListsItalic: t("unorderedListsItalic"),
    unorderedListsItalicTooltip: t("unorderedListsItalicTooltip"),
    unorderedListsBulletChar: t("unorderedListsBulletChar"),
    unorderedListsBulletCharTooltip: t("unorderedListsBulletCharTooltip"),
    unorderedListsBulletCharPlaceholder: t("unorderedListsBulletCharPlaceholder"),
    unorderedListsBulletFontSize: t("unorderedListsBulletFontSize"),
    unorderedListsBulletFontSizeTooltip: t("unorderedListsBulletFontSizeTooltip"),
    unorderedListsGap: t("unorderedListsGap"),
    unorderedListsGapTooltip: t("unorderedListsGapTooltip"),
    unorderedListsIndent: t("unorderedListsIndent"),
    unorderedListsIndentTooltip: t("unorderedListsIndentTooltip"),
    unorderedListsBulletVerticalOffset: t("unorderedListsBulletVerticalOffset"),
    unorderedListsBulletVerticalOffsetTooltip: t("unorderedListsBulletVerticalOffsetTooltip"),
    unorderedListsMarginTop: t("unorderedListsMarginTop"),
    unorderedListsMarginTopTooltip: t("unorderedListsMarginTopTooltip"),
    unorderedListsMarginBottom: t("unorderedListsMarginBottom"),
    unorderedListsMarginBottomTooltip: t("unorderedListsMarginBottomTooltip"),
    unorderedListsItemSpacing: t("unorderedListsItemSpacing"),
    unorderedListsItemSpacingTooltip: t("unorderedListsItemSpacingTooltip"),
    unorderedListsHangingIndent: t("unorderedListsHangingIndent"),
    unorderedListsHangingIndentTooltip: t("unorderedListsHangingIndentTooltip"),
    unorderedListLevel: t("unorderedListLevel"),
    unorderedListLevelBulletChar: t("unorderedListLevelBulletChar"),
    unorderedListLevelBulletCharTooltip: t("unorderedListLevelBulletCharTooltip"),
    unorderedListLevelFont: t("unorderedListLevelFont"),
    unorderedListLevelFontTooltip: t("unorderedListLevelFontTooltip"),
    unorderedListLevelFontSize: t("unorderedListLevelFontSize"),
    unorderedListLevelFontSizeTooltip: t("unorderedListLevelFontSizeTooltip"),
    unorderedListLevelColor: t("unorderedListLevelColor"),
    unorderedListLevelColorTooltip: t("unorderedListLevelColorTooltip"),
    unorderedListLevelFontWeight: t("unorderedListLevelFontWeight"),
    unorderedListLevelFontWeightTooltip: t("unorderedListLevelFontWeightTooltip"),
    unorderedListLevelItalic: t("unorderedListLevelItalic"),
    unorderedListLevelItalicTooltip: t("unorderedListLevelItalicTooltip"),
    unorderedListLevelIndent: t("unorderedListLevelIndent"),
    unorderedListLevelIndentTooltip: t("unorderedListLevelIndentTooltip"),
    unorderedListLevelVerticalOffset: t("unorderedListLevelVerticalOffset"),
    unorderedListLevelVerticalOffsetTooltip: t("unorderedListLevelVerticalOffsetTooltip"),
    taskLists: t("taskLists"),
    taskCheckboxChar: t("taskCheckboxChar"),
    taskCheckboxCharTooltip: t("taskCheckboxCharTooltip"),
    taskCheckboxCharPlaceholder: t("taskCheckboxCharPlaceholder"),
    taskCheckedChar: t("taskCheckedChar"),
    taskCheckedCharTooltip: t("taskCheckedCharTooltip"),
    taskCheckedCharPlaceholder: t("taskCheckedCharPlaceholder"),
    taskCompletedStrikethrough: t("taskCompletedStrikethrough"),
    taskCompletedStrikethroughTooltip: t("taskCompletedStrikethroughTooltip"),
    taskCompletedColor: t("taskCompletedColor"),
    taskCompletedColorTooltip: t("taskCompletedColorTooltip"),
    orderedLists: t("orderedLists"),
    orderedListsFont: t("orderedListsFont"),
    orderedListsFontTooltip: t("orderedListsFontTooltip"),
    orderedListsFontSearch: t("orderedListsFontSearch"),
    orderedListsFontNoResults: t("orderedListsFontNoResults"),
    orderedListsColor: t("orderedListsColor"),
    orderedListsColorTooltip: t("orderedListsColorTooltip"),
    orderedListsFontWeight: t("orderedListsFontWeight"),
    orderedListsFontWeightTooltip: t("orderedListsFontWeightTooltip"),
    orderedListsItalic: t("orderedListsItalic"),
    orderedListsItalicTooltip: t("orderedListsItalicTooltip"),
    orderedListsNumberFormat: t("orderedListsNumberFormat"),
    orderedListsNumberFormatTooltip: t("orderedListsNumberFormatTooltip"),
    orderedListsNumberFormatArabic: t("orderedListsNumberFormatArabic"),
    orderedListsNumberFormatLowerAlpha: t("orderedListsNumberFormatLowerAlpha"),
    orderedListsNumberFormatUpperAlpha: t("orderedListsNumberFormatUpperAlpha"),
    orderedListsNumberFormatLowerRoman: t("orderedListsNumberFormatLowerRoman"),
    orderedListsNumberFormatUpperRoman: t("orderedListsNumberFormatUpperRoman"),
    orderedListsSeparator: t("orderedListsSeparator"),
    orderedListsSeparatorTooltip: t("orderedListsSeparatorTooltip"),
    orderedListsSeparatorPlaceholder: t("orderedListsSeparatorPlaceholder"),
    orderedListsNumberFontSize: t("orderedListsNumberFontSize"),
    orderedListsNumberFontSizeTooltip: t("orderedListsNumberFontSizeTooltip"),
    orderedListsGap: t("orderedListsGap"),
    orderedListsGapTooltip: t("orderedListsGapTooltip"),
    orderedListsIndent: t("orderedListsIndent"),
    orderedListsIndentTooltip: t("orderedListsIndentTooltip"),
    orderedListsNumberVerticalOffset: t("orderedListsNumberVerticalOffset"),
    orderedListsNumberVerticalOffsetTooltip: t("orderedListsNumberVerticalOffsetTooltip"),
    orderedListsMarginTop: t("orderedListsMarginTop"),
    orderedListsMarginTopTooltip: t("orderedListsMarginTopTooltip"),
    orderedListsMarginBottom: t("orderedListsMarginBottom"),
    orderedListsMarginBottomTooltip: t("orderedListsMarginBottomTooltip"),
    orderedListsItemSpacing: t("orderedListsItemSpacing"),
    orderedListsItemSpacingTooltip: t("orderedListsItemSpacingTooltip"),
    orderedListsHangingIndent: t("orderedListsHangingIndent"),
    orderedListsHangingIndentTooltip: t("orderedListsHangingIndentTooltip"),
    orderedListLevel: t("orderedListLevel"),
    orderedListLevelNumberFormat: t("orderedListLevelNumberFormat"),
    orderedListLevelNumberFormatTooltip: t("orderedListLevelNumberFormatTooltip"),
    orderedListLevelSeparator: t("orderedListLevelSeparator"),
    orderedListLevelSeparatorTooltip: t("orderedListLevelSeparatorTooltip"),
    orderedListLevelFont: t("orderedListLevelFont"),
    orderedListLevelFontTooltip: t("orderedListLevelFontTooltip"),
    orderedListLevelFontSize: t("orderedListLevelFontSize"),
    orderedListLevelFontSizeTooltip: t("orderedListLevelFontSizeTooltip"),
    orderedListLevelColor: t("orderedListLevelColor"),
    orderedListLevelColorTooltip: t("orderedListLevelColorTooltip"),
    orderedListLevelFontWeight: t("orderedListLevelFontWeight"),
    orderedListLevelFontWeightTooltip: t("orderedListLevelFontWeightTooltip"),
    orderedListLevelItalic: t("orderedListLevelItalic"),
    orderedListLevelItalicTooltip: t("orderedListLevelItalicTooltip"),
    orderedListLevelIndent: t("orderedListLevelIndent"),
    orderedListLevelIndentTooltip: t("orderedListLevelIndentTooltip"),
    orderedListLevelVerticalOffset: t("orderedListLevelVerticalOffset"),
    orderedListLevelVerticalOffsetTooltip: t("orderedListLevelVerticalOffsetTooltip"),
    headingsTextAlign: t("headingsTextAlign"),
    headingsTextAlignTooltip: t("headingsTextAlignTooltip"),
    headingsTextAlignLeft: t("headingsTextAlignLeft"),
    headingsTextAlignJustify: t("headingsTextAlignJustify"),
    layout: t("layout"),
    layoutType: t("layoutType"),
    layoutTypeTooltip: t("layoutTypeTooltip"),
    layoutSingle: t("layoutSingle"),
    layoutDouble: t("layoutDouble"),
    layoutOneAndHalf: t("layoutOneAndHalf"),
    gutterWidth: t("gutterWidth"),
    gutterWidthTooltip: t("gutterWidthTooltip"),
    sideColumnPercent: t("sideColumnPercent"),
    sideColumnPercentTooltip: t("sideColumnPercentTooltip"),
    columnRule: t("columnRule"),
    columnRuleTooltip: t("columnRuleTooltip"),
    columnRuleColor: t("columnRuleColor"),
    columnRuleColorTooltip: t("columnRuleColorTooltip"),
    columnRuleLineWidth: t("columnRuleLineWidth"),
    columnRuleLineWidthTooltip: t("columnRuleLineWidthTooltip"),
    zoomIn: t("zoomIn"),
    zoomOut: t("zoomOut"),
    fitWidth: t("fitWidth"),
    fitHeight: t("fitHeight"),
    singlePage: t("singlePage"),
    doublePageSpread: t("doublePageSpread"),
    canvasToolbar: t("canvasToolbar"),
    bold: t("bold"),
    italic: t("italic"),
    heading: t("heading"),
    link: t("link"),
    code: t("code"),
    blockquote: t("blockquote"),
    orderedList: t("orderedList"),
    unorderedList: t("unorderedList"),
    undo: t("undo"),
    redo: t("redo"),
    save: t("save"),
    load: t("load"),
    exportFile: t("exportFile"),
    importFile: t("importFile"),
    reset: t("reset"),
    resetConfigConfirm: t("resetConfigConfirm"),
    resetSectionConfirm: t("resetSectionConfirm"),
    resetMarkdownConfirm: t("resetMarkdownConfirm"),
    colorPalette: t("colorPalette"),
    colorPaletteTooltip: t("colorPaletteTooltip"),
    colorPaletteEntryName: t("colorPaletteEntryName"),
    colorPaletteAdd: t("colorPaletteAdd"),
    colorPaletteRemove: t("colorPaletteRemove"),
    colorPaletteNewEntry: t("colorPaletteNewEntry"),
    colorPaletteLink: t("colorPaletteLink"),
    colorPaletteUnlink: t("colorPaletteUnlink"),
    colorPaletteNone: t("colorPaletteNone"),
    colorPaletteEditName: t("colorPaletteEditName"),
    colorPaletteDeleteConfirm: t("colorPaletteDeleteConfirm"),
    colorPaletteDeleteInUse: t("colorPaletteDeleteInUse"),
    colorPaletteDeleteInUseNote: t("colorPaletteDeleteInUseNote"),
  };

  return (
    <PostextSandbox
      initialMarkdown={initialMarkdown}
      labels={labels}
      locale={locale}
      themeToggle={<ThemeToggle />}
      languageSwitcher={<CompactLanguageSwitcher />}
      homeLink={
        <Link
          href="/"
          className="flex h-10 w-10 items-center justify-center rounded-md transition-colors focus-visible:outline-none focus-visible:ring-2"
          style={{ color: "var(--gilt)", outlineColor: "var(--accent-blue)" }}
          onMouseEnter={(e) => {
            e.currentTarget.style.backgroundColor = "var(--surface)";
          }}
          onMouseLeave={(e) => {
            e.currentTarget.style.backgroundColor = "transparent";
          }}
        >
          <span
            className="text-2xl font-black leading-none"
            style={{
              fontFamily:
                'var(--font-logo, var(--font-cormorant, "Cormorant Garamond", Georgia, serif))',
            }}
          >
            P
          </span>
        </Link>
      }
    />
  );
}
